// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statistics.proto

package org.tensorflow.metadata.v0;

public interface CommonStatisticsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.metadata.v0.CommonStatistics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The number of examples with at least one value for this feature.
   * </pre>
   *
   * <code>uint64 num_non_missing = 1;</code>
   * @return The numNonMissing.
   */
  long getNumNonMissing();

  /**
   * <pre>
   * The number of examples with no values for this feature.
   * </pre>
   *
   * <code>uint64 num_missing = 2;</code>
   * @return The numMissing.
   */
  long getNumMissing();

  /**
   * <pre>
   * The minimum number of values in a single example for this feature.
   * </pre>
   *
   * <code>uint64 min_num_values = 3;</code>
   * @return The minNumValues.
   */
  long getMinNumValues();

  /**
   * <pre>
   * The maximum number of values in a single example for this feature.
   * </pre>
   *
   * <code>uint64 max_num_values = 4;</code>
   * @return The maxNumValues.
   */
  long getMaxNumValues();

  /**
   * <pre>
   * The average number of values in a single example for this feature.
   * </pre>
   *
   * <code>float avg_num_values = 5;</code>
   * @return The avgNumValues.
   */
  float getAvgNumValues();

  /**
   * <pre>
   * tot_num_values = avg_num_values * num_non_missing.
   * This is calculated directly, so should have less numerical error.
   * </pre>
   *
   * <code>uint64 tot_num_values = 8;</code>
   * @return The totNumValues.
   */
  long getTotNumValues();

  /**
   * <pre>
   * The quantiles histogram for the number of values in this feature.
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.Histogram num_values_histogram = 6;</code>
   * @return Whether the numValuesHistogram field is set.
   */
  boolean hasNumValuesHistogram();
  /**
   * <pre>
   * The quantiles histogram for the number of values in this feature.
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.Histogram num_values_histogram = 6;</code>
   * @return The numValuesHistogram.
   */
  Histogram getNumValuesHistogram();
  /**
   * <pre>
   * The quantiles histogram for the number of values in this feature.
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.Histogram num_values_histogram = 6;</code>
   */
  HistogramOrBuilder getNumValuesHistogramOrBuilder();

  /**
   * <code>.tensorflow.metadata.v0.WeightedCommonStatistics weighted_common_stats = 7;</code>
   * @return Whether the weightedCommonStats field is set.
   */
  boolean hasWeightedCommonStats();
  /**
   * <code>.tensorflow.metadata.v0.WeightedCommonStatistics weighted_common_stats = 7;</code>
   * @return The weightedCommonStats.
   */
  WeightedCommonStatistics getWeightedCommonStats();
  /**
   * <code>.tensorflow.metadata.v0.WeightedCommonStatistics weighted_common_stats = 7;</code>
   */
  WeightedCommonStatisticsOrBuilder getWeightedCommonStatsOrBuilder();

  /**
   * <pre>
   * The histogram for the number of features in the feature list (only set if
   * this feature is a non-context feature from a tf.SequenceExample).
   * This is different from num_values_histogram, as num_values_histogram tracks
   * the count of all values for a feature in an example, whereas this tracks
   * the length of the feature list for this feature in an example (where each
   * feature list can contain multiple values).
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.Histogram feature_list_length_histogram = 9;</code>
   * @return Whether the featureListLengthHistogram field is set.
   */
  boolean hasFeatureListLengthHistogram();
  /**
   * <pre>
   * The histogram for the number of features in the feature list (only set if
   * this feature is a non-context feature from a tf.SequenceExample).
   * This is different from num_values_histogram, as num_values_histogram tracks
   * the count of all values for a feature in an example, whereas this tracks
   * the length of the feature list for this feature in an example (where each
   * feature list can contain multiple values).
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.Histogram feature_list_length_histogram = 9;</code>
   * @return The featureListLengthHistogram.
   */
  Histogram getFeatureListLengthHistogram();
  /**
   * <pre>
   * The histogram for the number of features in the feature list (only set if
   * this feature is a non-context feature from a tf.SequenceExample).
   * This is different from num_values_histogram, as num_values_histogram tracks
   * the count of all values for a feature in an example, whereas this tracks
   * the length of the feature list for this feature in an example (where each
   * feature list can contain multiple values).
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.Histogram feature_list_length_histogram = 9;</code>
   */
  HistogramOrBuilder getFeatureListLengthHistogramOrBuilder();

  /**
   * <pre>
   * Contains presence and valency stats for each nest level of the feature.
   * The first item corresponds to the outermost level, and by definition,
   * the stats it contains equals to the corresponding stats defined above.
   * May not be populated if the feature is of nest level 1.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.PresenceAndValencyStatistics presence_and_valency_stats = 10;</code>
   */
  java.util.List<PresenceAndValencyStatistics>
      getPresenceAndValencyStatsList();
  /**
   * <pre>
   * Contains presence and valency stats for each nest level of the feature.
   * The first item corresponds to the outermost level, and by definition,
   * the stats it contains equals to the corresponding stats defined above.
   * May not be populated if the feature is of nest level 1.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.PresenceAndValencyStatistics presence_and_valency_stats = 10;</code>
   */
  PresenceAndValencyStatistics getPresenceAndValencyStats(int index);
  /**
   * <pre>
   * Contains presence and valency stats for each nest level of the feature.
   * The first item corresponds to the outermost level, and by definition,
   * the stats it contains equals to the corresponding stats defined above.
   * May not be populated if the feature is of nest level 1.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.PresenceAndValencyStatistics presence_and_valency_stats = 10;</code>
   */
  int getPresenceAndValencyStatsCount();
  /**
   * <pre>
   * Contains presence and valency stats for each nest level of the feature.
   * The first item corresponds to the outermost level, and by definition,
   * the stats it contains equals to the corresponding stats defined above.
   * May not be populated if the feature is of nest level 1.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.PresenceAndValencyStatistics presence_and_valency_stats = 10;</code>
   */
  java.util.List<? extends PresenceAndValencyStatisticsOrBuilder>
      getPresenceAndValencyStatsOrBuilderList();
  /**
   * <pre>
   * Contains presence and valency stats for each nest level of the feature.
   * The first item corresponds to the outermost level, and by definition,
   * the stats it contains equals to the corresponding stats defined above.
   * May not be populated if the feature is of nest level 1.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.PresenceAndValencyStatistics presence_and_valency_stats = 10;</code>
   */
  PresenceAndValencyStatisticsOrBuilder getPresenceAndValencyStatsOrBuilder(
      int index);

  /**
   * <pre>
   * If not empty, it's parallel to presence_and_valency_stats.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.WeightedCommonStatistics weighted_presence_and_valency_stats = 11;</code>
   */
  java.util.List<WeightedCommonStatistics>
      getWeightedPresenceAndValencyStatsList();
  /**
   * <pre>
   * If not empty, it's parallel to presence_and_valency_stats.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.WeightedCommonStatistics weighted_presence_and_valency_stats = 11;</code>
   */
  WeightedCommonStatistics getWeightedPresenceAndValencyStats(int index);
  /**
   * <pre>
   * If not empty, it's parallel to presence_and_valency_stats.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.WeightedCommonStatistics weighted_presence_and_valency_stats = 11;</code>
   */
  int getWeightedPresenceAndValencyStatsCount();
  /**
   * <pre>
   * If not empty, it's parallel to presence_and_valency_stats.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.WeightedCommonStatistics weighted_presence_and_valency_stats = 11;</code>
   */
  java.util.List<? extends WeightedCommonStatisticsOrBuilder>
      getWeightedPresenceAndValencyStatsOrBuilderList();
  /**
   * <pre>
   * If not empty, it's parallel to presence_and_valency_stats.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.WeightedCommonStatistics weighted_presence_and_valency_stats = 11;</code>
   */
  WeightedCommonStatisticsOrBuilder getWeightedPresenceAndValencyStatsOrBuilder(
      int index);
}
