// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statistics.proto

package org.tensorflow.metadata.v0;

/**
 * <pre>
 * NextID: 8
 * </pre>
 *
 * Protobuf type {@code tensorflow.metadata.v0.CrossFeatureStatistics}
 */
public final class CrossFeatureStatistics extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.metadata.v0.CrossFeatureStatistics)
    CrossFeatureStatisticsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CrossFeatureStatistics.newBuilder() to construct.
  private CrossFeatureStatistics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CrossFeatureStatistics() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new CrossFeatureStatistics();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CrossFeatureStatistics(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            Path.Builder subBuilder = null;
            if (pathX_ != null) {
              subBuilder = pathX_.toBuilder();
            }
            pathX_ = input.readMessage(Path.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pathX_);
              pathX_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            Path.Builder subBuilder = null;
            if (pathY_ != null) {
              subBuilder = pathY_.toBuilder();
            }
            pathY_ = input.readMessage(Path.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pathY_);
              pathY_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            count_ = input.readUInt64();
            break;
          }
          case 34: {
            NumericCrossStatistics.Builder subBuilder = null;
            if (crossStatsCase_ == 4) {
              subBuilder = ((NumericCrossStatistics) crossStats_).toBuilder();
            }
            crossStats_ =
                input.readMessage(NumericCrossStatistics.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((NumericCrossStatistics) crossStats_);
              crossStats_ = subBuilder.buildPartial();
            }
            crossStatsCase_ = 4;
            break;
          }
          case 42: {
            CategoricalCrossStatistics.Builder subBuilder = null;
            if (crossStatsCase_ == 5) {
              subBuilder = ((CategoricalCrossStatistics) crossStats_).toBuilder();
            }
            crossStats_ =
                input.readMessage(CategoricalCrossStatistics.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((CategoricalCrossStatistics) crossStats_);
              crossStats_ = subBuilder.buildPartial();
            }
            crossStatsCase_ = 5;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Statistics.internal_static_tensorflow_metadata_v0_CrossFeatureStatistics_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Statistics.internal_static_tensorflow_metadata_v0_CrossFeatureStatistics_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CrossFeatureStatistics.class, Builder.class);
  }

  private int crossStatsCase_ = 0;
  private Object crossStats_;
  public enum CrossStatsCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    NUM_CROSS_STATS(4),
    CATEGORICAL_CROSS_STATS(5),
    CROSSSTATS_NOT_SET(0);
    private final int value;
    private CrossStatsCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static CrossStatsCase valueOf(int value) {
      return forNumber(value);
    }

    public static CrossStatsCase forNumber(int value) {
      switch (value) {
        case 4: return NUM_CROSS_STATS;
        case 5: return CATEGORICAL_CROSS_STATS;
        case 0: return CROSSSTATS_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public CrossStatsCase
  getCrossStatsCase() {
    return CrossStatsCase.forNumber(
        crossStatsCase_);
  }

  public static final int PATH_X_FIELD_NUMBER = 1;
  private Path pathX_;
  /**
   * <pre>
   * The path of feature x.
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.Path path_x = 1;</code>
   * @return Whether the pathX field is set.
   */
  @Override
  public boolean hasPathX() {
    return pathX_ != null;
  }
  /**
   * <pre>
   * The path of feature x.
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.Path path_x = 1;</code>
   * @return The pathX.
   */
  @Override
  public Path getPathX() {
    return pathX_ == null ? Path.getDefaultInstance() : pathX_;
  }
  /**
   * <pre>
   * The path of feature x.
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.Path path_x = 1;</code>
   */
  @Override
  public PathOrBuilder getPathXOrBuilder() {
    return getPathX();
  }

  public static final int PATH_Y_FIELD_NUMBER = 2;
  private Path pathY_;
  /**
   * <pre>
   * The path of feature y.
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.Path path_y = 2;</code>
   * @return Whether the pathY field is set.
   */
  @Override
  public boolean hasPathY() {
    return pathY_ != null;
  }
  /**
   * <pre>
   * The path of feature y.
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.Path path_y = 2;</code>
   * @return The pathY.
   */
  @Override
  public Path getPathY() {
    return pathY_ == null ? Path.getDefaultInstance() : pathY_;
  }
  /**
   * <pre>
   * The path of feature y.
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.Path path_y = 2;</code>
   */
  @Override
  public PathOrBuilder getPathYOrBuilder() {
    return getPathY();
  }

  public static final int COUNT_FIELD_NUMBER = 3;
  private long count_;
  /**
   * <pre>
   * Number of occurrences of this feature cross in the data. If any of
   * the features in the cross is missing, the example is ignored.
   * </pre>
   *
   * <code>uint64 count = 3;</code>
   * @return The count.
   */
  @Override
  public long getCount() {
    return count_;
  }

  public static final int NUM_CROSS_STATS_FIELD_NUMBER = 4;
  /**
   * <code>.tensorflow.metadata.v0.NumericCrossStatistics num_cross_stats = 4;</code>
   * @return Whether the numCrossStats field is set.
   */
  @Override
  public boolean hasNumCrossStats() {
    return crossStatsCase_ == 4;
  }
  /**
   * <code>.tensorflow.metadata.v0.NumericCrossStatistics num_cross_stats = 4;</code>
   * @return The numCrossStats.
   */
  @Override
  public NumericCrossStatistics getNumCrossStats() {
    if (crossStatsCase_ == 4) {
       return (NumericCrossStatistics) crossStats_;
    }
    return NumericCrossStatistics.getDefaultInstance();
  }
  /**
   * <code>.tensorflow.metadata.v0.NumericCrossStatistics num_cross_stats = 4;</code>
   */
  @Override
  public NumericCrossStatisticsOrBuilder getNumCrossStatsOrBuilder() {
    if (crossStatsCase_ == 4) {
       return (NumericCrossStatistics) crossStats_;
    }
    return NumericCrossStatistics.getDefaultInstance();
  }

  public static final int CATEGORICAL_CROSS_STATS_FIELD_NUMBER = 5;
  /**
   * <code>.tensorflow.metadata.v0.CategoricalCrossStatistics categorical_cross_stats = 5;</code>
   * @return Whether the categoricalCrossStats field is set.
   */
  @Override
  public boolean hasCategoricalCrossStats() {
    return crossStatsCase_ == 5;
  }
  /**
   * <code>.tensorflow.metadata.v0.CategoricalCrossStatistics categorical_cross_stats = 5;</code>
   * @return The categoricalCrossStats.
   */
  @Override
  public CategoricalCrossStatistics getCategoricalCrossStats() {
    if (crossStatsCase_ == 5) {
       return (CategoricalCrossStatistics) crossStats_;
    }
    return CategoricalCrossStatistics.getDefaultInstance();
  }
  /**
   * <code>.tensorflow.metadata.v0.CategoricalCrossStatistics categorical_cross_stats = 5;</code>
   */
  @Override
  public CategoricalCrossStatisticsOrBuilder getCategoricalCrossStatsOrBuilder() {
    if (crossStatsCase_ == 5) {
       return (CategoricalCrossStatistics) crossStats_;
    }
    return CategoricalCrossStatistics.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (pathX_ != null) {
      output.writeMessage(1, getPathX());
    }
    if (pathY_ != null) {
      output.writeMessage(2, getPathY());
    }
    if (count_ != 0L) {
      output.writeUInt64(3, count_);
    }
    if (crossStatsCase_ == 4) {
      output.writeMessage(4, (NumericCrossStatistics) crossStats_);
    }
    if (crossStatsCase_ == 5) {
      output.writeMessage(5, (CategoricalCrossStatistics) crossStats_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (pathX_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPathX());
    }
    if (pathY_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPathY());
    }
    if (count_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, count_);
    }
    if (crossStatsCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (NumericCrossStatistics) crossStats_);
    }
    if (crossStatsCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (CategoricalCrossStatistics) crossStats_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CrossFeatureStatistics)) {
      return super.equals(obj);
    }
    CrossFeatureStatistics other = (CrossFeatureStatistics) obj;

    if (hasPathX() != other.hasPathX()) return false;
    if (hasPathX()) {
      if (!getPathX()
          .equals(other.getPathX())) return false;
    }
    if (hasPathY() != other.hasPathY()) return false;
    if (hasPathY()) {
      if (!getPathY()
          .equals(other.getPathY())) return false;
    }
    if (getCount()
        != other.getCount()) return false;
    if (!getCrossStatsCase().equals(other.getCrossStatsCase())) return false;
    switch (crossStatsCase_) {
      case 4:
        if (!getNumCrossStats()
            .equals(other.getNumCrossStats())) return false;
        break;
      case 5:
        if (!getCategoricalCrossStats()
            .equals(other.getCategoricalCrossStats())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPathX()) {
      hash = (37 * hash) + PATH_X_FIELD_NUMBER;
      hash = (53 * hash) + getPathX().hashCode();
    }
    if (hasPathY()) {
      hash = (37 * hash) + PATH_Y_FIELD_NUMBER;
      hash = (53 * hash) + getPathY().hashCode();
    }
    hash = (37 * hash) + COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCount());
    switch (crossStatsCase_) {
      case 4:
        hash = (37 * hash) + NUM_CROSS_STATS_FIELD_NUMBER;
        hash = (53 * hash) + getNumCrossStats().hashCode();
        break;
      case 5:
        hash = (37 * hash) + CATEGORICAL_CROSS_STATS_FIELD_NUMBER;
        hash = (53 * hash) + getCategoricalCrossStats().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CrossFeatureStatistics parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CrossFeatureStatistics parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CrossFeatureStatistics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CrossFeatureStatistics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CrossFeatureStatistics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CrossFeatureStatistics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CrossFeatureStatistics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CrossFeatureStatistics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CrossFeatureStatistics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CrossFeatureStatistics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CrossFeatureStatistics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CrossFeatureStatistics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CrossFeatureStatistics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * NextID: 8
   * </pre>
   *
   * Protobuf type {@code tensorflow.metadata.v0.CrossFeatureStatistics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.metadata.v0.CrossFeatureStatistics)
      CrossFeatureStatisticsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Statistics.internal_static_tensorflow_metadata_v0_CrossFeatureStatistics_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Statistics.internal_static_tensorflow_metadata_v0_CrossFeatureStatistics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CrossFeatureStatistics.class, Builder.class);
    }

    // Construct using org.tensorflow.metadata.v0.CrossFeatureStatistics.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (pathXBuilder_ == null) {
        pathX_ = null;
      } else {
        pathX_ = null;
        pathXBuilder_ = null;
      }
      if (pathYBuilder_ == null) {
        pathY_ = null;
      } else {
        pathY_ = null;
        pathYBuilder_ = null;
      }
      count_ = 0L;

      crossStatsCase_ = 0;
      crossStats_ = null;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Statistics.internal_static_tensorflow_metadata_v0_CrossFeatureStatistics_descriptor;
    }

    @Override
    public CrossFeatureStatistics getDefaultInstanceForType() {
      return CrossFeatureStatistics.getDefaultInstance();
    }

    @Override
    public CrossFeatureStatistics build() {
      CrossFeatureStatistics result = buildPartial();
      if (!result.isInitialized()) {
        throw Builder.newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CrossFeatureStatistics buildPartial() {
      CrossFeatureStatistics result = new CrossFeatureStatistics(this);
      if (pathXBuilder_ == null) {
        result.pathX_ = pathX_;
      } else {
        result.pathX_ = pathXBuilder_.build();
      }
      if (pathYBuilder_ == null) {
        result.pathY_ = pathY_;
      } else {
        result.pathY_ = pathYBuilder_.build();
      }
      result.count_ = count_;
      if (crossStatsCase_ == 4) {
        if (numCrossStatsBuilder_ == null) {
          result.crossStats_ = crossStats_;
        } else {
          result.crossStats_ = numCrossStatsBuilder_.build();
        }
      }
      if (crossStatsCase_ == 5) {
        if (categoricalCrossStatsBuilder_ == null) {
          result.crossStats_ = crossStats_;
        } else {
          result.crossStats_ = categoricalCrossStatsBuilder_.build();
        }
      }
      result.crossStatsCase_ = crossStatsCase_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CrossFeatureStatistics) {
        return mergeFrom((CrossFeatureStatistics)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CrossFeatureStatistics other) {
      if (other == CrossFeatureStatistics.getDefaultInstance()) return this;
      if (other.hasPathX()) {
        mergePathX(other.getPathX());
      }
      if (other.hasPathY()) {
        mergePathY(other.getPathY());
      }
      if (other.getCount() != 0L) {
        setCount(other.getCount());
      }
      switch (other.getCrossStatsCase()) {
        case NUM_CROSS_STATS: {
          mergeNumCrossStats(other.getNumCrossStats());
          break;
        }
        case CATEGORICAL_CROSS_STATS: {
          mergeCategoricalCrossStats(other.getCategoricalCrossStats());
          break;
        }
        case CROSSSTATS_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CrossFeatureStatistics parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CrossFeatureStatistics) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int crossStatsCase_ = 0;
    private Object crossStats_;
    public CrossStatsCase
        getCrossStatsCase() {
      return CrossStatsCase.forNumber(
          crossStatsCase_);
    }

    public Builder clearCrossStats() {
      crossStatsCase_ = 0;
      crossStats_ = null;
      onChanged();
      return this;
    }


    private Path pathX_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Path, Path.Builder, PathOrBuilder> pathXBuilder_;
    /**
     * <pre>
     * The path of feature x.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path_x = 1;</code>
     * @return Whether the pathX field is set.
     */
    public boolean hasPathX() {
      return pathXBuilder_ != null || pathX_ != null;
    }
    /**
     * <pre>
     * The path of feature x.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path_x = 1;</code>
     * @return The pathX.
     */
    public Path getPathX() {
      if (pathXBuilder_ == null) {
        return pathX_ == null ? Path.getDefaultInstance() : pathX_;
      } else {
        return pathXBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The path of feature x.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path_x = 1;</code>
     */
    public Builder setPathX(Path value) {
      if (pathXBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pathX_ = value;
        onChanged();
      } else {
        pathXBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The path of feature x.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path_x = 1;</code>
     */
    public Builder setPathX(
        Path.Builder builderForValue) {
      if (pathXBuilder_ == null) {
        pathX_ = builderForValue.build();
        onChanged();
      } else {
        pathXBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The path of feature x.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path_x = 1;</code>
     */
    public Builder mergePathX(Path value) {
      if (pathXBuilder_ == null) {
        if (pathX_ != null) {
          pathX_ =
            Path.newBuilder(pathX_).mergeFrom(value).buildPartial();
        } else {
          pathX_ = value;
        }
        onChanged();
      } else {
        pathXBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The path of feature x.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path_x = 1;</code>
     */
    public Builder clearPathX() {
      if (pathXBuilder_ == null) {
        pathX_ = null;
        onChanged();
      } else {
        pathX_ = null;
        pathXBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The path of feature x.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path_x = 1;</code>
     */
    public Path.Builder getPathXBuilder() {
      
      onChanged();
      return getPathXFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The path of feature x.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path_x = 1;</code>
     */
    public PathOrBuilder getPathXOrBuilder() {
      if (pathXBuilder_ != null) {
        return pathXBuilder_.getMessageOrBuilder();
      } else {
        return pathX_ == null ?
            Path.getDefaultInstance() : pathX_;
      }
    }
    /**
     * <pre>
     * The path of feature x.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path_x = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Path, Path.Builder, PathOrBuilder>
        getPathXFieldBuilder() {
      if (pathXBuilder_ == null) {
        pathXBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Path, Path.Builder, PathOrBuilder>(
                getPathX(),
                getParentForChildren(),
                isClean());
        pathX_ = null;
      }
      return pathXBuilder_;
    }

    private Path pathY_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Path, Path.Builder, PathOrBuilder> pathYBuilder_;
    /**
     * <pre>
     * The path of feature y.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path_y = 2;</code>
     * @return Whether the pathY field is set.
     */
    public boolean hasPathY() {
      return pathYBuilder_ != null || pathY_ != null;
    }
    /**
     * <pre>
     * The path of feature y.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path_y = 2;</code>
     * @return The pathY.
     */
    public Path getPathY() {
      if (pathYBuilder_ == null) {
        return pathY_ == null ? Path.getDefaultInstance() : pathY_;
      } else {
        return pathYBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The path of feature y.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path_y = 2;</code>
     */
    public Builder setPathY(Path value) {
      if (pathYBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pathY_ = value;
        onChanged();
      } else {
        pathYBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The path of feature y.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path_y = 2;</code>
     */
    public Builder setPathY(
        Path.Builder builderForValue) {
      if (pathYBuilder_ == null) {
        pathY_ = builderForValue.build();
        onChanged();
      } else {
        pathYBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The path of feature y.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path_y = 2;</code>
     */
    public Builder mergePathY(Path value) {
      if (pathYBuilder_ == null) {
        if (pathY_ != null) {
          pathY_ =
            Path.newBuilder(pathY_).mergeFrom(value).buildPartial();
        } else {
          pathY_ = value;
        }
        onChanged();
      } else {
        pathYBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The path of feature y.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path_y = 2;</code>
     */
    public Builder clearPathY() {
      if (pathYBuilder_ == null) {
        pathY_ = null;
        onChanged();
      } else {
        pathY_ = null;
        pathYBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The path of feature y.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path_y = 2;</code>
     */
    public Path.Builder getPathYBuilder() {
      
      onChanged();
      return getPathYFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The path of feature y.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path_y = 2;</code>
     */
    public PathOrBuilder getPathYOrBuilder() {
      if (pathYBuilder_ != null) {
        return pathYBuilder_.getMessageOrBuilder();
      } else {
        return pathY_ == null ?
            Path.getDefaultInstance() : pathY_;
      }
    }
    /**
     * <pre>
     * The path of feature y.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path_y = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Path, Path.Builder, PathOrBuilder>
        getPathYFieldBuilder() {
      if (pathYBuilder_ == null) {
        pathYBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Path, Path.Builder, PathOrBuilder>(
                getPathY(),
                getParentForChildren(),
                isClean());
        pathY_ = null;
      }
      return pathYBuilder_;
    }

    private long count_ ;
    /**
     * <pre>
     * Number of occurrences of this feature cross in the data. If any of
     * the features in the cross is missing, the example is ignored.
     * </pre>
     *
     * <code>uint64 count = 3;</code>
     * @return The count.
     */
    @Override
    public long getCount() {
      return count_;
    }
    /**
     * <pre>
     * Number of occurrences of this feature cross in the data. If any of
     * the features in the cross is missing, the example is ignored.
     * </pre>
     *
     * <code>uint64 count = 3;</code>
     * @param value The count to set.
     * @return This builder for chaining.
     */
    public Builder setCount(long value) {
      
      count_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Number of occurrences of this feature cross in the data. If any of
     * the features in the cross is missing, the example is ignored.
     * </pre>
     *
     * <code>uint64 count = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCount() {
      
      count_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        NumericCrossStatistics, NumericCrossStatistics.Builder, NumericCrossStatisticsOrBuilder> numCrossStatsBuilder_;
    /**
     * <code>.tensorflow.metadata.v0.NumericCrossStatistics num_cross_stats = 4;</code>
     * @return Whether the numCrossStats field is set.
     */
    @Override
    public boolean hasNumCrossStats() {
      return crossStatsCase_ == 4;
    }
    /**
     * <code>.tensorflow.metadata.v0.NumericCrossStatistics num_cross_stats = 4;</code>
     * @return The numCrossStats.
     */
    @Override
    public NumericCrossStatistics getNumCrossStats() {
      if (numCrossStatsBuilder_ == null) {
        if (crossStatsCase_ == 4) {
          return (NumericCrossStatistics) crossStats_;
        }
        return NumericCrossStatistics.getDefaultInstance();
      } else {
        if (crossStatsCase_ == 4) {
          return numCrossStatsBuilder_.getMessage();
        }
        return NumericCrossStatistics.getDefaultInstance();
      }
    }
    /**
     * <code>.tensorflow.metadata.v0.NumericCrossStatistics num_cross_stats = 4;</code>
     */
    public Builder setNumCrossStats(NumericCrossStatistics value) {
      if (numCrossStatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        crossStats_ = value;
        onChanged();
      } else {
        numCrossStatsBuilder_.setMessage(value);
      }
      crossStatsCase_ = 4;
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.NumericCrossStatistics num_cross_stats = 4;</code>
     */
    public Builder setNumCrossStats(
        NumericCrossStatistics.Builder builderForValue) {
      if (numCrossStatsBuilder_ == null) {
        crossStats_ = builderForValue.build();
        onChanged();
      } else {
        numCrossStatsBuilder_.setMessage(builderForValue.build());
      }
      crossStatsCase_ = 4;
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.NumericCrossStatistics num_cross_stats = 4;</code>
     */
    public Builder mergeNumCrossStats(NumericCrossStatistics value) {
      if (numCrossStatsBuilder_ == null) {
        if (crossStatsCase_ == 4 &&
            crossStats_ != NumericCrossStatistics.getDefaultInstance()) {
          crossStats_ = NumericCrossStatistics.newBuilder((NumericCrossStatistics) crossStats_)
              .mergeFrom(value).buildPartial();
        } else {
          crossStats_ = value;
        }
        onChanged();
      } else {
        if (crossStatsCase_ == 4) {
          numCrossStatsBuilder_.mergeFrom(value);
        } else {
          numCrossStatsBuilder_.setMessage(value);
        }
      }
      crossStatsCase_ = 4;
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.NumericCrossStatistics num_cross_stats = 4;</code>
     */
    public Builder clearNumCrossStats() {
      if (numCrossStatsBuilder_ == null) {
        if (crossStatsCase_ == 4) {
          crossStatsCase_ = 0;
          crossStats_ = null;
          onChanged();
        }
      } else {
        if (crossStatsCase_ == 4) {
          crossStatsCase_ = 0;
          crossStats_ = null;
        }
        numCrossStatsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.NumericCrossStatistics num_cross_stats = 4;</code>
     */
    public NumericCrossStatistics.Builder getNumCrossStatsBuilder() {
      return getNumCrossStatsFieldBuilder().getBuilder();
    }
    /**
     * <code>.tensorflow.metadata.v0.NumericCrossStatistics num_cross_stats = 4;</code>
     */
    @Override
    public NumericCrossStatisticsOrBuilder getNumCrossStatsOrBuilder() {
      if ((crossStatsCase_ == 4) && (numCrossStatsBuilder_ != null)) {
        return numCrossStatsBuilder_.getMessageOrBuilder();
      } else {
        if (crossStatsCase_ == 4) {
          return (NumericCrossStatistics) crossStats_;
        }
        return NumericCrossStatistics.getDefaultInstance();
      }
    }
    /**
     * <code>.tensorflow.metadata.v0.NumericCrossStatistics num_cross_stats = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        NumericCrossStatistics, NumericCrossStatistics.Builder, NumericCrossStatisticsOrBuilder>
        getNumCrossStatsFieldBuilder() {
      if (numCrossStatsBuilder_ == null) {
        if (!(crossStatsCase_ == 4)) {
          crossStats_ = NumericCrossStatistics.getDefaultInstance();
        }
        numCrossStatsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            NumericCrossStatistics, NumericCrossStatistics.Builder, NumericCrossStatisticsOrBuilder>(
                (NumericCrossStatistics) crossStats_,
                getParentForChildren(),
                isClean());
        crossStats_ = null;
      }
      crossStatsCase_ = 4;
      onChanged();;
      return numCrossStatsBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        CategoricalCrossStatistics, CategoricalCrossStatistics.Builder, CategoricalCrossStatisticsOrBuilder> categoricalCrossStatsBuilder_;
    /**
     * <code>.tensorflow.metadata.v0.CategoricalCrossStatistics categorical_cross_stats = 5;</code>
     * @return Whether the categoricalCrossStats field is set.
     */
    @Override
    public boolean hasCategoricalCrossStats() {
      return crossStatsCase_ == 5;
    }
    /**
     * <code>.tensorflow.metadata.v0.CategoricalCrossStatistics categorical_cross_stats = 5;</code>
     * @return The categoricalCrossStats.
     */
    @Override
    public CategoricalCrossStatistics getCategoricalCrossStats() {
      if (categoricalCrossStatsBuilder_ == null) {
        if (crossStatsCase_ == 5) {
          return (CategoricalCrossStatistics) crossStats_;
        }
        return CategoricalCrossStatistics.getDefaultInstance();
      } else {
        if (crossStatsCase_ == 5) {
          return categoricalCrossStatsBuilder_.getMessage();
        }
        return CategoricalCrossStatistics.getDefaultInstance();
      }
    }
    /**
     * <code>.tensorflow.metadata.v0.CategoricalCrossStatistics categorical_cross_stats = 5;</code>
     */
    public Builder setCategoricalCrossStats(CategoricalCrossStatistics value) {
      if (categoricalCrossStatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        crossStats_ = value;
        onChanged();
      } else {
        categoricalCrossStatsBuilder_.setMessage(value);
      }
      crossStatsCase_ = 5;
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.CategoricalCrossStatistics categorical_cross_stats = 5;</code>
     */
    public Builder setCategoricalCrossStats(
        CategoricalCrossStatistics.Builder builderForValue) {
      if (categoricalCrossStatsBuilder_ == null) {
        crossStats_ = builderForValue.build();
        onChanged();
      } else {
        categoricalCrossStatsBuilder_.setMessage(builderForValue.build());
      }
      crossStatsCase_ = 5;
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.CategoricalCrossStatistics categorical_cross_stats = 5;</code>
     */
    public Builder mergeCategoricalCrossStats(CategoricalCrossStatistics value) {
      if (categoricalCrossStatsBuilder_ == null) {
        if (crossStatsCase_ == 5 &&
            crossStats_ != CategoricalCrossStatistics.getDefaultInstance()) {
          crossStats_ = CategoricalCrossStatistics.newBuilder((CategoricalCrossStatistics) crossStats_)
              .mergeFrom(value).buildPartial();
        } else {
          crossStats_ = value;
        }
        onChanged();
      } else {
        if (crossStatsCase_ == 5) {
          categoricalCrossStatsBuilder_.mergeFrom(value);
        } else {
          categoricalCrossStatsBuilder_.setMessage(value);
        }
      }
      crossStatsCase_ = 5;
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.CategoricalCrossStatistics categorical_cross_stats = 5;</code>
     */
    public Builder clearCategoricalCrossStats() {
      if (categoricalCrossStatsBuilder_ == null) {
        if (crossStatsCase_ == 5) {
          crossStatsCase_ = 0;
          crossStats_ = null;
          onChanged();
        }
      } else {
        if (crossStatsCase_ == 5) {
          crossStatsCase_ = 0;
          crossStats_ = null;
        }
        categoricalCrossStatsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.CategoricalCrossStatistics categorical_cross_stats = 5;</code>
     */
    public CategoricalCrossStatistics.Builder getCategoricalCrossStatsBuilder() {
      return getCategoricalCrossStatsFieldBuilder().getBuilder();
    }
    /**
     * <code>.tensorflow.metadata.v0.CategoricalCrossStatistics categorical_cross_stats = 5;</code>
     */
    @Override
    public CategoricalCrossStatisticsOrBuilder getCategoricalCrossStatsOrBuilder() {
      if ((crossStatsCase_ == 5) && (categoricalCrossStatsBuilder_ != null)) {
        return categoricalCrossStatsBuilder_.getMessageOrBuilder();
      } else {
        if (crossStatsCase_ == 5) {
          return (CategoricalCrossStatistics) crossStats_;
        }
        return CategoricalCrossStatistics.getDefaultInstance();
      }
    }
    /**
     * <code>.tensorflow.metadata.v0.CategoricalCrossStatistics categorical_cross_stats = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        CategoricalCrossStatistics, CategoricalCrossStatistics.Builder, CategoricalCrossStatisticsOrBuilder>
        getCategoricalCrossStatsFieldBuilder() {
      if (categoricalCrossStatsBuilder_ == null) {
        if (!(crossStatsCase_ == 5)) {
          crossStats_ = CategoricalCrossStatistics.getDefaultInstance();
        }
        categoricalCrossStatsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            CategoricalCrossStatistics, CategoricalCrossStatistics.Builder, CategoricalCrossStatisticsOrBuilder>(
                (CategoricalCrossStatistics) crossStats_,
                getParentForChildren(),
                isClean());
        crossStats_ = null;
      }
      crossStatsCase_ = 5;
      onChanged();;
      return categoricalCrossStatsBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.metadata.v0.CrossFeatureStatistics)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.metadata.v0.CrossFeatureStatistics)
  private static final CrossFeatureStatistics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CrossFeatureStatistics();
  }

  public static CrossFeatureStatistics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CrossFeatureStatistics>
      PARSER = new com.google.protobuf.AbstractParser<CrossFeatureStatistics>() {
    @Override
    public CrossFeatureStatistics parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CrossFeatureStatistics(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CrossFeatureStatistics> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CrossFeatureStatistics> getParserForType() {
    return PARSER;
  }

  @Override
  public CrossFeatureStatistics getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

