// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statistics.proto

package org.tensorflow.metadata.v0;

public interface CrossFeatureStatisticsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.metadata.v0.CrossFeatureStatistics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The path of feature x.
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.Path path_x = 1;</code>
   * @return Whether the pathX field is set.
   */
  boolean hasPathX();
  /**
   * <pre>
   * The path of feature x.
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.Path path_x = 1;</code>
   * @return The pathX.
   */
  Path getPathX();
  /**
   * <pre>
   * The path of feature x.
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.Path path_x = 1;</code>
   */
  PathOrBuilder getPathXOrBuilder();

  /**
   * <pre>
   * The path of feature y.
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.Path path_y = 2;</code>
   * @return Whether the pathY field is set.
   */
  boolean hasPathY();
  /**
   * <pre>
   * The path of feature y.
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.Path path_y = 2;</code>
   * @return The pathY.
   */
  Path getPathY();
  /**
   * <pre>
   * The path of feature y.
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.Path path_y = 2;</code>
   */
  PathOrBuilder getPathYOrBuilder();

  /**
   * <pre>
   * Number of occurrences of this feature cross in the data. If any of
   * the features in the cross is missing, the example is ignored.
   * </pre>
   *
   * <code>uint64 count = 3;</code>
   * @return The count.
   */
  long getCount();

  /**
   * <code>.tensorflow.metadata.v0.NumericCrossStatistics num_cross_stats = 4;</code>
   * @return Whether the numCrossStats field is set.
   */
  boolean hasNumCrossStats();
  /**
   * <code>.tensorflow.metadata.v0.NumericCrossStatistics num_cross_stats = 4;</code>
   * @return The numCrossStats.
   */
  NumericCrossStatistics getNumCrossStats();
  /**
   * <code>.tensorflow.metadata.v0.NumericCrossStatistics num_cross_stats = 4;</code>
   */
  NumericCrossStatisticsOrBuilder getNumCrossStatsOrBuilder();

  /**
   * <code>.tensorflow.metadata.v0.CategoricalCrossStatistics categorical_cross_stats = 5;</code>
   * @return Whether the categoricalCrossStats field is set.
   */
  boolean hasCategoricalCrossStats();
  /**
   * <code>.tensorflow.metadata.v0.CategoricalCrossStatistics categorical_cross_stats = 5;</code>
   * @return The categoricalCrossStats.
   */
  CategoricalCrossStatistics getCategoricalCrossStats();
  /**
   * <code>.tensorflow.metadata.v0.CategoricalCrossStatistics categorical_cross_stats = 5;</code>
   */
  CategoricalCrossStatisticsOrBuilder getCategoricalCrossStatsOrBuilder();

  public CrossFeatureStatistics.CrossStatsCase getCrossStatsCase();
}
