// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statistics.proto

package org.tensorflow.metadata.v0;

/**
 * <pre>
 * A list of features statistics for different datasets. If you wish to compare
 * different datasets using this list, then the DatasetFeatureStatistics
 * entries should all contain the same list of features.
 * LINT.IfChange
 * </pre>
 *
 * Protobuf type {@code tensorflow.metadata.v0.DatasetFeatureStatisticsList}
 */
public final class DatasetFeatureStatisticsList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.metadata.v0.DatasetFeatureStatisticsList)
    DatasetFeatureStatisticsListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DatasetFeatureStatisticsList.newBuilder() to construct.
  private DatasetFeatureStatisticsList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DatasetFeatureStatisticsList() {
    datasets_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new DatasetFeatureStatisticsList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DatasetFeatureStatisticsList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              datasets_ = new java.util.ArrayList<DatasetFeatureStatistics>();
              mutable_bitField0_ |= 0x00000001;
            }
            datasets_.add(
                input.readMessage(DatasetFeatureStatistics.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        datasets_ = java.util.Collections.unmodifiableList(datasets_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Statistics.internal_static_tensorflow_metadata_v0_DatasetFeatureStatisticsList_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Statistics.internal_static_tensorflow_metadata_v0_DatasetFeatureStatisticsList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            DatasetFeatureStatisticsList.class, Builder.class);
  }

  public static final int DATASETS_FIELD_NUMBER = 1;
  private java.util.List<DatasetFeatureStatistics> datasets_;
  /**
   * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
   */
  @Override
  public java.util.List<DatasetFeatureStatistics> getDatasetsList() {
    return datasets_;
  }
  /**
   * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
   */
  @Override
  public java.util.List<? extends DatasetFeatureStatisticsOrBuilder>
      getDatasetsOrBuilderList() {
    return datasets_;
  }
  /**
   * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
   */
  @Override
  public int getDatasetsCount() {
    return datasets_.size();
  }
  /**
   * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
   */
  @Override
  public DatasetFeatureStatistics getDatasets(int index) {
    return datasets_.get(index);
  }
  /**
   * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
   */
  @Override
  public DatasetFeatureStatisticsOrBuilder getDatasetsOrBuilder(
      int index) {
    return datasets_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < datasets_.size(); i++) {
      output.writeMessage(1, datasets_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < datasets_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, datasets_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof DatasetFeatureStatisticsList)) {
      return super.equals(obj);
    }
    DatasetFeatureStatisticsList other = (DatasetFeatureStatisticsList) obj;

    if (!getDatasetsList()
        .equals(other.getDatasetsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDatasetsCount() > 0) {
      hash = (37 * hash) + DATASETS_FIELD_NUMBER;
      hash = (53 * hash) + getDatasetsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static DatasetFeatureStatisticsList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DatasetFeatureStatisticsList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DatasetFeatureStatisticsList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DatasetFeatureStatisticsList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DatasetFeatureStatisticsList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DatasetFeatureStatisticsList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DatasetFeatureStatisticsList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DatasetFeatureStatisticsList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static DatasetFeatureStatisticsList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static DatasetFeatureStatisticsList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static DatasetFeatureStatisticsList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DatasetFeatureStatisticsList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(DatasetFeatureStatisticsList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A list of features statistics for different datasets. If you wish to compare
   * different datasets using this list, then the DatasetFeatureStatistics
   * entries should all contain the same list of features.
   * LINT.IfChange
   * </pre>
   *
   * Protobuf type {@code tensorflow.metadata.v0.DatasetFeatureStatisticsList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.metadata.v0.DatasetFeatureStatisticsList)
      DatasetFeatureStatisticsListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Statistics.internal_static_tensorflow_metadata_v0_DatasetFeatureStatisticsList_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Statistics.internal_static_tensorflow_metadata_v0_DatasetFeatureStatisticsList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DatasetFeatureStatisticsList.class, Builder.class);
    }

    // Construct using org.tensorflow.metadata.v0.DatasetFeatureStatisticsList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDatasetsFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (datasetsBuilder_ == null) {
        datasets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        datasetsBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Statistics.internal_static_tensorflow_metadata_v0_DatasetFeatureStatisticsList_descriptor;
    }

    @Override
    public DatasetFeatureStatisticsList getDefaultInstanceForType() {
      return DatasetFeatureStatisticsList.getDefaultInstance();
    }

    @Override
    public DatasetFeatureStatisticsList build() {
      DatasetFeatureStatisticsList result = buildPartial();
      if (!result.isInitialized()) {
        throw Builder.newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public DatasetFeatureStatisticsList buildPartial() {
      DatasetFeatureStatisticsList result = new DatasetFeatureStatisticsList(this);
      int from_bitField0_ = bitField0_;
      if (datasetsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          datasets_ = java.util.Collections.unmodifiableList(datasets_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.datasets_ = datasets_;
      } else {
        result.datasets_ = datasetsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DatasetFeatureStatisticsList) {
        return mergeFrom((DatasetFeatureStatisticsList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DatasetFeatureStatisticsList other) {
      if (other == DatasetFeatureStatisticsList.getDefaultInstance()) return this;
      if (datasetsBuilder_ == null) {
        if (!other.datasets_.isEmpty()) {
          if (datasets_.isEmpty()) {
            datasets_ = other.datasets_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDatasetsIsMutable();
            datasets_.addAll(other.datasets_);
          }
          onChanged();
        }
      } else {
        if (!other.datasets_.isEmpty()) {
          if (datasetsBuilder_.isEmpty()) {
            datasetsBuilder_.dispose();
            datasetsBuilder_ = null;
            datasets_ = other.datasets_;
            bitField0_ = (bitField0_ & ~0x00000001);
            datasetsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDatasetsFieldBuilder() : null;
          } else {
            datasetsBuilder_.addAllMessages(other.datasets_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      DatasetFeatureStatisticsList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (DatasetFeatureStatisticsList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<DatasetFeatureStatistics> datasets_ =
      java.util.Collections.emptyList();
    private void ensureDatasetsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        datasets_ = new java.util.ArrayList<DatasetFeatureStatistics>(datasets_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        DatasetFeatureStatistics, DatasetFeatureStatistics.Builder, DatasetFeatureStatisticsOrBuilder> datasetsBuilder_;

    /**
     * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
     */
    public java.util.List<DatasetFeatureStatistics> getDatasetsList() {
      if (datasetsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(datasets_);
      } else {
        return datasetsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
     */
    public int getDatasetsCount() {
      if (datasetsBuilder_ == null) {
        return datasets_.size();
      } else {
        return datasetsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
     */
    public DatasetFeatureStatistics getDatasets(int index) {
      if (datasetsBuilder_ == null) {
        return datasets_.get(index);
      } else {
        return datasetsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
     */
    public Builder setDatasets(
        int index, DatasetFeatureStatistics value) {
      if (datasetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDatasetsIsMutable();
        datasets_.set(index, value);
        onChanged();
      } else {
        datasetsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
     */
    public Builder setDatasets(
        int index, DatasetFeatureStatistics.Builder builderForValue) {
      if (datasetsBuilder_ == null) {
        ensureDatasetsIsMutable();
        datasets_.set(index, builderForValue.build());
        onChanged();
      } else {
        datasetsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
     */
    public Builder addDatasets(DatasetFeatureStatistics value) {
      if (datasetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDatasetsIsMutable();
        datasets_.add(value);
        onChanged();
      } else {
        datasetsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
     */
    public Builder addDatasets(
        int index, DatasetFeatureStatistics value) {
      if (datasetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDatasetsIsMutable();
        datasets_.add(index, value);
        onChanged();
      } else {
        datasetsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
     */
    public Builder addDatasets(
        DatasetFeatureStatistics.Builder builderForValue) {
      if (datasetsBuilder_ == null) {
        ensureDatasetsIsMutable();
        datasets_.add(builderForValue.build());
        onChanged();
      } else {
        datasetsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
     */
    public Builder addDatasets(
        int index, DatasetFeatureStatistics.Builder builderForValue) {
      if (datasetsBuilder_ == null) {
        ensureDatasetsIsMutable();
        datasets_.add(index, builderForValue.build());
        onChanged();
      } else {
        datasetsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
     */
    public Builder addAllDatasets(
        Iterable<? extends DatasetFeatureStatistics> values) {
      if (datasetsBuilder_ == null) {
        ensureDatasetsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, datasets_);
        onChanged();
      } else {
        datasetsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
     */
    public Builder clearDatasets() {
      if (datasetsBuilder_ == null) {
        datasets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        datasetsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
     */
    public Builder removeDatasets(int index) {
      if (datasetsBuilder_ == null) {
        ensureDatasetsIsMutable();
        datasets_.remove(index);
        onChanged();
      } else {
        datasetsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
     */
    public DatasetFeatureStatistics.Builder getDatasetsBuilder(
        int index) {
      return getDatasetsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
     */
    public DatasetFeatureStatisticsOrBuilder getDatasetsOrBuilder(
        int index) {
      if (datasetsBuilder_ == null) {
        return datasets_.get(index);  } else {
        return datasetsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
     */
    public java.util.List<? extends DatasetFeatureStatisticsOrBuilder>
         getDatasetsOrBuilderList() {
      if (datasetsBuilder_ != null) {
        return datasetsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(datasets_);
      }
    }
    /**
     * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
     */
    public DatasetFeatureStatistics.Builder addDatasetsBuilder() {
      return getDatasetsFieldBuilder().addBuilder(
          DatasetFeatureStatistics.getDefaultInstance());
    }
    /**
     * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
     */
    public DatasetFeatureStatistics.Builder addDatasetsBuilder(
        int index) {
      return getDatasetsFieldBuilder().addBuilder(
          index, DatasetFeatureStatistics.getDefaultInstance());
    }
    /**
     * <code>repeated .tensorflow.metadata.v0.DatasetFeatureStatistics datasets = 1;</code>
     */
    public java.util.List<DatasetFeatureStatistics.Builder>
         getDatasetsBuilderList() {
      return getDatasetsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        DatasetFeatureStatistics, DatasetFeatureStatistics.Builder, DatasetFeatureStatisticsOrBuilder>
        getDatasetsFieldBuilder() {
      if (datasetsBuilder_ == null) {
        datasetsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            DatasetFeatureStatistics, DatasetFeatureStatistics.Builder, DatasetFeatureStatisticsOrBuilder>(
                datasets_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        datasets_ = null;
      }
      return datasetsBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.metadata.v0.DatasetFeatureStatisticsList)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.metadata.v0.DatasetFeatureStatisticsList)
  private static final DatasetFeatureStatisticsList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DatasetFeatureStatisticsList();
  }

  public static DatasetFeatureStatisticsList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DatasetFeatureStatisticsList>
      PARSER = new com.google.protobuf.AbstractParser<DatasetFeatureStatisticsList>() {
    @Override
    public DatasetFeatureStatisticsList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DatasetFeatureStatisticsList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DatasetFeatureStatisticsList> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<DatasetFeatureStatisticsList> getParserForType() {
    return PARSER;
  }

  @Override
  public DatasetFeatureStatisticsList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

