// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statistics.proto

package org.tensorflow.metadata.v0;

import com.google.protobuf.AbstractMessageLite;

/**
 * <pre>
 * The feature statistics for a single dataset.
 * </pre>
 *
 * Protobuf type {@code tensorflow.metadata.v0.DatasetFeatureStatistics}
 */
public final class DatasetFeatureStatistics extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.metadata.v0.DatasetFeatureStatistics)
    DatasetFeatureStatisticsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DatasetFeatureStatistics.newBuilder() to construct.
  private DatasetFeatureStatistics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DatasetFeatureStatistics() {
    name_ = "";
    features_ = java.util.Collections.emptyList();
    crossFeatures_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new DatasetFeatureStatistics();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DatasetFeatureStatistics(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 16: {

            numExamples_ = input.readUInt64();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              features_ = new java.util.ArrayList<FeatureNameStatistics>();
              mutable_bitField0_ |= 0x00000001;
            }
            features_.add(
                input.readMessage(FeatureNameStatistics.parser(), extensionRegistry));
            break;
          }
          case 33: {

            weightedNumExamples_ = input.readDouble();
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              crossFeatures_ = new java.util.ArrayList<CrossFeatureStatistics>();
              mutable_bitField0_ |= 0x00000002;
            }
            crossFeatures_.add(
                input.readMessage(CrossFeatureStatistics.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        features_ = java.util.Collections.unmodifiableList(features_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        crossFeatures_ = java.util.Collections.unmodifiableList(crossFeatures_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Statistics.internal_static_tensorflow_metadata_v0_DatasetFeatureStatistics_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Statistics.internal_static_tensorflow_metadata_v0_DatasetFeatureStatistics_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            DatasetFeatureStatistics.class, Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile Object name_;
  /**
   * <pre>
   * The name of the dataset.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  @Override
  public String getName() {
    Object ref = name_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The name of the dataset.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    Object ref = name_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUM_EXAMPLES_FIELD_NUMBER = 2;
  private long numExamples_;
  /**
   * <pre>
   * The number of examples in the dataset.
   * </pre>
   *
   * <code>uint64 num_examples = 2;</code>
   * @return The numExamples.
   */
  @Override
  public long getNumExamples() {
    return numExamples_;
  }

  public static final int WEIGHTED_NUM_EXAMPLES_FIELD_NUMBER = 4;
  private double weightedNumExamples_;
  /**
   * <pre>
   * Only valid if the weight feature was specified.
   * Treats a missing weighted feature as zero.
   * </pre>
   *
   * <code>double weighted_num_examples = 4;</code>
   * @return The weightedNumExamples.
   */
  @Override
  public double getWeightedNumExamples() {
    return weightedNumExamples_;
  }

  public static final int FEATURES_FIELD_NUMBER = 3;
  private java.util.List<FeatureNameStatistics> features_;
  /**
   * <pre>
   * The feature statistics for the dataset.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
   */
  @Override
  public java.util.List<FeatureNameStatistics> getFeaturesList() {
    return features_;
  }
  /**
   * <pre>
   * The feature statistics for the dataset.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
   */
  @Override
  public java.util.List<? extends FeatureNameStatisticsOrBuilder>
      getFeaturesOrBuilderList() {
    return features_;
  }
  /**
   * <pre>
   * The feature statistics for the dataset.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
   */
  @Override
  public int getFeaturesCount() {
    return features_.size();
  }
  /**
   * <pre>
   * The feature statistics for the dataset.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
   */
  @Override
  public FeatureNameStatistics getFeatures(int index) {
    return features_.get(index);
  }
  /**
   * <pre>
   * The feature statistics for the dataset.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
   */
  @Override
  public FeatureNameStatisticsOrBuilder getFeaturesOrBuilder(
      int index) {
    return features_.get(index);
  }

  public static final int CROSS_FEATURES_FIELD_NUMBER = 5;
  private java.util.List<CrossFeatureStatistics> crossFeatures_;
  /**
   * <pre>
   * Cross feature statistics for the dataset.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
   */
  @Override
  public java.util.List<CrossFeatureStatistics> getCrossFeaturesList() {
    return crossFeatures_;
  }
  /**
   * <pre>
   * Cross feature statistics for the dataset.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
   */
  @Override
  public java.util.List<? extends CrossFeatureStatisticsOrBuilder>
      getCrossFeaturesOrBuilderList() {
    return crossFeatures_;
  }
  /**
   * <pre>
   * Cross feature statistics for the dataset.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
   */
  @Override
  public int getCrossFeaturesCount() {
    return crossFeatures_.size();
  }
  /**
   * <pre>
   * Cross feature statistics for the dataset.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
   */
  @Override
  public CrossFeatureStatistics getCrossFeatures(int index) {
    return crossFeatures_.get(index);
  }
  /**
   * <pre>
   * Cross feature statistics for the dataset.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
   */
  @Override
  public CrossFeatureStatisticsOrBuilder getCrossFeaturesOrBuilder(
      int index) {
    return crossFeatures_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (numExamples_ != 0L) {
      output.writeUInt64(2, numExamples_);
    }
    for (int i = 0; i < features_.size(); i++) {
      output.writeMessage(3, features_.get(i));
    }
    if (Double.doubleToRawLongBits(weightedNumExamples_) != 0) {
      output.writeDouble(4, weightedNumExamples_);
    }
    for (int i = 0; i < crossFeatures_.size(); i++) {
      output.writeMessage(5, crossFeatures_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (numExamples_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, numExamples_);
    }
    for (int i = 0; i < features_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, features_.get(i));
    }
    if (Double.doubleToRawLongBits(weightedNumExamples_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, weightedNumExamples_);
    }
    for (int i = 0; i < crossFeatures_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, crossFeatures_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof DatasetFeatureStatistics)) {
      return super.equals(obj);
    }
    DatasetFeatureStatistics other = (DatasetFeatureStatistics) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (getNumExamples()
        != other.getNumExamples()) return false;
    if (Double.doubleToLongBits(getWeightedNumExamples())
        != Double.doubleToLongBits(
            other.getWeightedNumExamples())) return false;
    if (!getFeaturesList()
        .equals(other.getFeaturesList())) return false;
    if (!getCrossFeaturesList()
        .equals(other.getCrossFeaturesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + NUM_EXAMPLES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNumExamples());
    hash = (37 * hash) + WEIGHTED_NUM_EXAMPLES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getWeightedNumExamples()));
    if (getFeaturesCount() > 0) {
      hash = (37 * hash) + FEATURES_FIELD_NUMBER;
      hash = (53 * hash) + getFeaturesList().hashCode();
    }
    if (getCrossFeaturesCount() > 0) {
      hash = (37 * hash) + CROSS_FEATURES_FIELD_NUMBER;
      hash = (53 * hash) + getCrossFeaturesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static DatasetFeatureStatistics parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DatasetFeatureStatistics parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DatasetFeatureStatistics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DatasetFeatureStatistics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DatasetFeatureStatistics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DatasetFeatureStatistics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DatasetFeatureStatistics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DatasetFeatureStatistics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static DatasetFeatureStatistics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static DatasetFeatureStatistics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static DatasetFeatureStatistics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DatasetFeatureStatistics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(DatasetFeatureStatistics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The feature statistics for a single dataset.
   * </pre>
   *
   * Protobuf type {@code tensorflow.metadata.v0.DatasetFeatureStatistics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.metadata.v0.DatasetFeatureStatistics)
      DatasetFeatureStatisticsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Statistics.internal_static_tensorflow_metadata_v0_DatasetFeatureStatistics_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Statistics.internal_static_tensorflow_metadata_v0_DatasetFeatureStatistics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DatasetFeatureStatistics.class, Builder.class);
    }

    // Construct using org.tensorflow.metadata.v0.DatasetFeatureStatistics.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFeaturesFieldBuilder();
        getCrossFeaturesFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      name_ = "";

      numExamples_ = 0L;

      weightedNumExamples_ = 0D;

      if (featuresBuilder_ == null) {
        features_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        featuresBuilder_.clear();
      }
      if (crossFeaturesBuilder_ == null) {
        crossFeatures_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        crossFeaturesBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Statistics.internal_static_tensorflow_metadata_v0_DatasetFeatureStatistics_descriptor;
    }

    @Override
    public DatasetFeatureStatistics getDefaultInstanceForType() {
      return DatasetFeatureStatistics.getDefaultInstance();
    }

    @Override
    public DatasetFeatureStatistics build() {
      DatasetFeatureStatistics result = buildPartial();
      if (!result.isInitialized()) {
        throw Builder.newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public DatasetFeatureStatistics buildPartial() {
      DatasetFeatureStatistics result = new DatasetFeatureStatistics(this);
      int from_bitField0_ = bitField0_;
      result.name_ = name_;
      result.numExamples_ = numExamples_;
      result.weightedNumExamples_ = weightedNumExamples_;
      if (featuresBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          features_ = java.util.Collections.unmodifiableList(features_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.features_ = features_;
      } else {
        result.features_ = featuresBuilder_.build();
      }
      if (crossFeaturesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          crossFeatures_ = java.util.Collections.unmodifiableList(crossFeatures_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.crossFeatures_ = crossFeatures_;
      } else {
        result.crossFeatures_ = crossFeaturesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DatasetFeatureStatistics) {
        return mergeFrom((DatasetFeatureStatistics)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DatasetFeatureStatistics other) {
      if (other == DatasetFeatureStatistics.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getNumExamples() != 0L) {
        setNumExamples(other.getNumExamples());
      }
      if (other.getWeightedNumExamples() != 0D) {
        setWeightedNumExamples(other.getWeightedNumExamples());
      }
      if (featuresBuilder_ == null) {
        if (!other.features_.isEmpty()) {
          if (features_.isEmpty()) {
            features_ = other.features_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFeaturesIsMutable();
            features_.addAll(other.features_);
          }
          onChanged();
        }
      } else {
        if (!other.features_.isEmpty()) {
          if (featuresBuilder_.isEmpty()) {
            featuresBuilder_.dispose();
            featuresBuilder_ = null;
            features_ = other.features_;
            bitField0_ = (bitField0_ & ~0x00000001);
            featuresBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFeaturesFieldBuilder() : null;
          } else {
            featuresBuilder_.addAllMessages(other.features_);
          }
        }
      }
      if (crossFeaturesBuilder_ == null) {
        if (!other.crossFeatures_.isEmpty()) {
          if (crossFeatures_.isEmpty()) {
            crossFeatures_ = other.crossFeatures_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureCrossFeaturesIsMutable();
            crossFeatures_.addAll(other.crossFeatures_);
          }
          onChanged();
        }
      } else {
        if (!other.crossFeatures_.isEmpty()) {
          if (crossFeaturesBuilder_.isEmpty()) {
            crossFeaturesBuilder_.dispose();
            crossFeaturesBuilder_ = null;
            crossFeatures_ = other.crossFeatures_;
            bitField0_ = (bitField0_ & ~0x00000002);
            crossFeaturesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCrossFeaturesFieldBuilder() : null;
          } else {
            crossFeaturesBuilder_.addAllMessages(other.crossFeatures_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      DatasetFeatureStatistics parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (DatasetFeatureStatistics) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object name_ = "";
    /**
     * <pre>
     * The name of the dataset.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    public String getName() {
      Object ref = name_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * The name of the dataset.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The name of the dataset.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the dataset.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the dataset.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  AbstractMessageLite.checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private long numExamples_ ;
    /**
     * <pre>
     * The number of examples in the dataset.
     * </pre>
     *
     * <code>uint64 num_examples = 2;</code>
     * @return The numExamples.
     */
    @Override
    public long getNumExamples() {
      return numExamples_;
    }
    /**
     * <pre>
     * The number of examples in the dataset.
     * </pre>
     *
     * <code>uint64 num_examples = 2;</code>
     * @param value The numExamples to set.
     * @return This builder for chaining.
     */
    public Builder setNumExamples(long value) {
      
      numExamples_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The number of examples in the dataset.
     * </pre>
     *
     * <code>uint64 num_examples = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumExamples() {
      
      numExamples_ = 0L;
      onChanged();
      return this;
    }

    private double weightedNumExamples_ ;
    /**
     * <pre>
     * Only valid if the weight feature was specified.
     * Treats a missing weighted feature as zero.
     * </pre>
     *
     * <code>double weighted_num_examples = 4;</code>
     * @return The weightedNumExamples.
     */
    @Override
    public double getWeightedNumExamples() {
      return weightedNumExamples_;
    }
    /**
     * <pre>
     * Only valid if the weight feature was specified.
     * Treats a missing weighted feature as zero.
     * </pre>
     *
     * <code>double weighted_num_examples = 4;</code>
     * @param value The weightedNumExamples to set.
     * @return This builder for chaining.
     */
    public Builder setWeightedNumExamples(double value) {
      
      weightedNumExamples_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Only valid if the weight feature was specified.
     * Treats a missing weighted feature as zero.
     * </pre>
     *
     * <code>double weighted_num_examples = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeightedNumExamples() {
      
      weightedNumExamples_ = 0D;
      onChanged();
      return this;
    }

    private java.util.List<FeatureNameStatistics> features_ =
      java.util.Collections.emptyList();
    private void ensureFeaturesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        features_ = new java.util.ArrayList<FeatureNameStatistics>(features_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        FeatureNameStatistics, FeatureNameStatistics.Builder, FeatureNameStatisticsOrBuilder> featuresBuilder_;

    /**
     * <pre>
     * The feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
     */
    public java.util.List<FeatureNameStatistics> getFeaturesList() {
      if (featuresBuilder_ == null) {
        return java.util.Collections.unmodifiableList(features_);
      } else {
        return featuresBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
     */
    public int getFeaturesCount() {
      if (featuresBuilder_ == null) {
        return features_.size();
      } else {
        return featuresBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
     */
    public FeatureNameStatistics getFeatures(int index) {
      if (featuresBuilder_ == null) {
        return features_.get(index);
      } else {
        return featuresBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
     */
    public Builder setFeatures(
        int index, FeatureNameStatistics value) {
      if (featuresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeaturesIsMutable();
        features_.set(index, value);
        onChanged();
      } else {
        featuresBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
     */
    public Builder setFeatures(
        int index, FeatureNameStatistics.Builder builderForValue) {
      if (featuresBuilder_ == null) {
        ensureFeaturesIsMutable();
        features_.set(index, builderForValue.build());
        onChanged();
      } else {
        featuresBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
     */
    public Builder addFeatures(FeatureNameStatistics value) {
      if (featuresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeaturesIsMutable();
        features_.add(value);
        onChanged();
      } else {
        featuresBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
     */
    public Builder addFeatures(
        int index, FeatureNameStatistics value) {
      if (featuresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeaturesIsMutable();
        features_.add(index, value);
        onChanged();
      } else {
        featuresBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
     */
    public Builder addFeatures(
        FeatureNameStatistics.Builder builderForValue) {
      if (featuresBuilder_ == null) {
        ensureFeaturesIsMutable();
        features_.add(builderForValue.build());
        onChanged();
      } else {
        featuresBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
     */
    public Builder addFeatures(
        int index, FeatureNameStatistics.Builder builderForValue) {
      if (featuresBuilder_ == null) {
        ensureFeaturesIsMutable();
        features_.add(index, builderForValue.build());
        onChanged();
      } else {
        featuresBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
     */
    public Builder addAllFeatures(
        Iterable<? extends FeatureNameStatistics> values) {
      if (featuresBuilder_ == null) {
        ensureFeaturesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, features_);
        onChanged();
      } else {
        featuresBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
     */
    public Builder clearFeatures() {
      if (featuresBuilder_ == null) {
        features_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        featuresBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
     */
    public Builder removeFeatures(int index) {
      if (featuresBuilder_ == null) {
        ensureFeaturesIsMutable();
        features_.remove(index);
        onChanged();
      } else {
        featuresBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
     */
    public FeatureNameStatistics.Builder getFeaturesBuilder(
        int index) {
      return getFeaturesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
     */
    public FeatureNameStatisticsOrBuilder getFeaturesOrBuilder(
        int index) {
      if (featuresBuilder_ == null) {
        return features_.get(index);  } else {
        return featuresBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
     */
    public java.util.List<? extends FeatureNameStatisticsOrBuilder>
         getFeaturesOrBuilderList() {
      if (featuresBuilder_ != null) {
        return featuresBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(features_);
      }
    }
    /**
     * <pre>
     * The feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
     */
    public FeatureNameStatistics.Builder addFeaturesBuilder() {
      return getFeaturesFieldBuilder().addBuilder(
          FeatureNameStatistics.getDefaultInstance());
    }
    /**
     * <pre>
     * The feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
     */
    public FeatureNameStatistics.Builder addFeaturesBuilder(
        int index) {
      return getFeaturesFieldBuilder().addBuilder(
          index, FeatureNameStatistics.getDefaultInstance());
    }
    /**
     * <pre>
     * The feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.FeatureNameStatistics features = 3;</code>
     */
    public java.util.List<FeatureNameStatistics.Builder>
         getFeaturesBuilderList() {
      return getFeaturesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        FeatureNameStatistics, FeatureNameStatistics.Builder, FeatureNameStatisticsOrBuilder>
        getFeaturesFieldBuilder() {
      if (featuresBuilder_ == null) {
        featuresBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            FeatureNameStatistics, FeatureNameStatistics.Builder, FeatureNameStatisticsOrBuilder>(
                features_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        features_ = null;
      }
      return featuresBuilder_;
    }

    private java.util.List<CrossFeatureStatistics> crossFeatures_ =
      java.util.Collections.emptyList();
    private void ensureCrossFeaturesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        crossFeatures_ = new java.util.ArrayList<CrossFeatureStatistics>(crossFeatures_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        CrossFeatureStatistics, CrossFeatureStatistics.Builder, CrossFeatureStatisticsOrBuilder> crossFeaturesBuilder_;

    /**
     * <pre>
     * Cross feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
     */
    public java.util.List<CrossFeatureStatistics> getCrossFeaturesList() {
      if (crossFeaturesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(crossFeatures_);
      } else {
        return crossFeaturesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Cross feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
     */
    public int getCrossFeaturesCount() {
      if (crossFeaturesBuilder_ == null) {
        return crossFeatures_.size();
      } else {
        return crossFeaturesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Cross feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
     */
    public CrossFeatureStatistics getCrossFeatures(int index) {
      if (crossFeaturesBuilder_ == null) {
        return crossFeatures_.get(index);
      } else {
        return crossFeaturesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Cross feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
     */
    public Builder setCrossFeatures(
        int index, CrossFeatureStatistics value) {
      if (crossFeaturesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCrossFeaturesIsMutable();
        crossFeatures_.set(index, value);
        onChanged();
      } else {
        crossFeaturesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Cross feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
     */
    public Builder setCrossFeatures(
        int index, CrossFeatureStatistics.Builder builderForValue) {
      if (crossFeaturesBuilder_ == null) {
        ensureCrossFeaturesIsMutable();
        crossFeatures_.set(index, builderForValue.build());
        onChanged();
      } else {
        crossFeaturesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Cross feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
     */
    public Builder addCrossFeatures(CrossFeatureStatistics value) {
      if (crossFeaturesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCrossFeaturesIsMutable();
        crossFeatures_.add(value);
        onChanged();
      } else {
        crossFeaturesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Cross feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
     */
    public Builder addCrossFeatures(
        int index, CrossFeatureStatistics value) {
      if (crossFeaturesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCrossFeaturesIsMutable();
        crossFeatures_.add(index, value);
        onChanged();
      } else {
        crossFeaturesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Cross feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
     */
    public Builder addCrossFeatures(
        CrossFeatureStatistics.Builder builderForValue) {
      if (crossFeaturesBuilder_ == null) {
        ensureCrossFeaturesIsMutable();
        crossFeatures_.add(builderForValue.build());
        onChanged();
      } else {
        crossFeaturesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Cross feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
     */
    public Builder addCrossFeatures(
        int index, CrossFeatureStatistics.Builder builderForValue) {
      if (crossFeaturesBuilder_ == null) {
        ensureCrossFeaturesIsMutable();
        crossFeatures_.add(index, builderForValue.build());
        onChanged();
      } else {
        crossFeaturesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Cross feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
     */
    public Builder addAllCrossFeatures(
        Iterable<? extends CrossFeatureStatistics> values) {
      if (crossFeaturesBuilder_ == null) {
        ensureCrossFeaturesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, crossFeatures_);
        onChanged();
      } else {
        crossFeaturesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Cross feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
     */
    public Builder clearCrossFeatures() {
      if (crossFeaturesBuilder_ == null) {
        crossFeatures_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        crossFeaturesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Cross feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
     */
    public Builder removeCrossFeatures(int index) {
      if (crossFeaturesBuilder_ == null) {
        ensureCrossFeaturesIsMutable();
        crossFeatures_.remove(index);
        onChanged();
      } else {
        crossFeaturesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Cross feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
     */
    public CrossFeatureStatistics.Builder getCrossFeaturesBuilder(
        int index) {
      return getCrossFeaturesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Cross feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
     */
    public CrossFeatureStatisticsOrBuilder getCrossFeaturesOrBuilder(
        int index) {
      if (crossFeaturesBuilder_ == null) {
        return crossFeatures_.get(index);  } else {
        return crossFeaturesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Cross feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
     */
    public java.util.List<? extends CrossFeatureStatisticsOrBuilder>
         getCrossFeaturesOrBuilderList() {
      if (crossFeaturesBuilder_ != null) {
        return crossFeaturesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(crossFeatures_);
      }
    }
    /**
     * <pre>
     * Cross feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
     */
    public CrossFeatureStatistics.Builder addCrossFeaturesBuilder() {
      return getCrossFeaturesFieldBuilder().addBuilder(
          CrossFeatureStatistics.getDefaultInstance());
    }
    /**
     * <pre>
     * Cross feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
     */
    public CrossFeatureStatistics.Builder addCrossFeaturesBuilder(
        int index) {
      return getCrossFeaturesFieldBuilder().addBuilder(
          index, CrossFeatureStatistics.getDefaultInstance());
    }
    /**
     * <pre>
     * Cross feature statistics for the dataset.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CrossFeatureStatistics cross_features = 5;</code>
     */
    public java.util.List<CrossFeatureStatistics.Builder>
         getCrossFeaturesBuilderList() {
      return getCrossFeaturesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        CrossFeatureStatistics, CrossFeatureStatistics.Builder, CrossFeatureStatisticsOrBuilder>
        getCrossFeaturesFieldBuilder() {
      if (crossFeaturesBuilder_ == null) {
        crossFeaturesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            CrossFeatureStatistics, CrossFeatureStatistics.Builder, CrossFeatureStatisticsOrBuilder>(
                crossFeatures_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        crossFeatures_ = null;
      }
      return crossFeaturesBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.metadata.v0.DatasetFeatureStatistics)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.metadata.v0.DatasetFeatureStatistics)
  private static final DatasetFeatureStatistics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DatasetFeatureStatistics();
  }

  public static DatasetFeatureStatistics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DatasetFeatureStatistics>
      PARSER = new com.google.protobuf.AbstractParser<DatasetFeatureStatistics>() {
    @Override
    public DatasetFeatureStatistics parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DatasetFeatureStatistics(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DatasetFeatureStatistics> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<DatasetFeatureStatistics> getParserForType() {
    return PARSER;
  }

  @Override
  public DatasetFeatureStatistics getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

