// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statistics.proto

package org.tensorflow.metadata.v0;

import com.google.protobuf.AbstractMessageLite;

/**
 * <pre>
 * The complete set of statistics for a given feature name for a dataset.
 * NextID: 11
 * </pre>
 *
 * Protobuf type {@code tensorflow.metadata.v0.FeatureNameStatistics}
 */
public final class FeatureNameStatistics extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.metadata.v0.FeatureNameStatistics)
    FeatureNameStatisticsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FeatureNameStatistics.newBuilder() to construct.
  private FeatureNameStatistics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FeatureNameStatistics() {
    type_ = 0;
    customStats_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new FeatureNameStatistics();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FeatureNameStatistics(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();
            fieldIdCase_ = 1;
            fieldId_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 26: {
            NumericStatistics.Builder subBuilder = null;
            if (statsCase_ == 3) {
              subBuilder = ((NumericStatistics) stats_).toBuilder();
            }
            stats_ =
                input.readMessage(NumericStatistics.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((NumericStatistics) stats_);
              stats_ = subBuilder.buildPartial();
            }
            statsCase_ = 3;
            break;
          }
          case 34: {
            StringStatistics.Builder subBuilder = null;
            if (statsCase_ == 4) {
              subBuilder = ((StringStatistics) stats_).toBuilder();
            }
            stats_ =
                input.readMessage(StringStatistics.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((StringStatistics) stats_);
              stats_ = subBuilder.buildPartial();
            }
            statsCase_ = 4;
            break;
          }
          case 42: {
            BytesStatistics.Builder subBuilder = null;
            if (statsCase_ == 5) {
              subBuilder = ((BytesStatistics) stats_).toBuilder();
            }
            stats_ =
                input.readMessage(BytesStatistics.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((BytesStatistics) stats_);
              stats_ = subBuilder.buildPartial();
            }
            statsCase_ = 5;
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              customStats_ = new java.util.ArrayList<CustomStatistic>();
              mutable_bitField0_ |= 0x00000001;
            }
            customStats_.add(
                input.readMessage(CustomStatistic.parser(), extensionRegistry));
            break;
          }
          case 58: {
            StructStatistics.Builder subBuilder = null;
            if (statsCase_ == 7) {
              subBuilder = ((StructStatistics) stats_).toBuilder();
            }
            stats_ =
                input.readMessage(StructStatistics.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((StructStatistics) stats_);
              stats_ = subBuilder.buildPartial();
            }
            statsCase_ = 7;
            break;
          }
          case 66: {
            Path.Builder subBuilder = null;
            if (fieldIdCase_ == 8) {
              subBuilder = ((Path) fieldId_).toBuilder();
            }
            fieldId_ =
                input.readMessage(Path.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((Path) fieldId_);
              fieldId_ = subBuilder.buildPartial();
            }
            fieldIdCase_ = 8;
            break;
          }
          case 82: {
            DerivedFeatureSource.Builder subBuilder = null;
            if (validationDerivedSource_ != null) {
              subBuilder = validationDerivedSource_.toBuilder();
            }
            validationDerivedSource_ = input.readMessage(DerivedFeatureSource.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(validationDerivedSource_);
              validationDerivedSource_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        customStats_ = java.util.Collections.unmodifiableList(customStats_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Statistics.internal_static_tensorflow_metadata_v0_FeatureNameStatistics_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Statistics.internal_static_tensorflow_metadata_v0_FeatureNameStatistics_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            FeatureNameStatistics.class, Builder.class);
  }

  /**
   * <pre>
   * The types supported by the feature statistics. When aggregating
   * tf.Examples, if the bytelist contains a string, it is recommended to encode
   * it here as STRING instead of BYTES in order to calculate string-specific
   * statistical measures.
   * </pre>
   *
   * Protobuf enum {@code tensorflow.metadata.v0.FeatureNameStatistics.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>INT = 0;</code>
     */
    INT(0),
    /**
     * <code>FLOAT = 1;</code>
     */
    FLOAT(1),
    /**
     * <code>STRING = 2;</code>
     */
    STRING(2),
    /**
     * <code>BYTES = 3;</code>
     */
    BYTES(3),
    /**
     * <code>STRUCT = 4;</code>
     */
    STRUCT(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>INT = 0;</code>
     */
    public static final int INT_VALUE = 0;
    /**
     * <code>FLOAT = 1;</code>
     */
    public static final int FLOAT_VALUE = 1;
    /**
     * <code>STRING = 2;</code>
     */
    public static final int STRING_VALUE = 2;
    /**
     * <code>BYTES = 3;</code>
     */
    public static final int BYTES_VALUE = 3;
    /**
     * <code>STRUCT = 4;</code>
     */
    public static final int STRUCT_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return INT;
        case 1: return FLOAT;
        case 2: return STRING;
        case 3: return BYTES;
        case 4: return STRUCT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return FeatureNameStatistics.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:tensorflow.metadata.v0.FeatureNameStatistics.Type)
  }

  private int fieldIdCase_ = 0;
  private Object fieldId_;
  public enum FieldIdCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    NAME(1),
    PATH(8),
    FIELDID_NOT_SET(0);
    private final int value;
    private FieldIdCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static FieldIdCase valueOf(int value) {
      return forNumber(value);
    }

    public static FieldIdCase forNumber(int value) {
      switch (value) {
        case 1: return NAME;
        case 8: return PATH;
        case 0: return FIELDID_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public FieldIdCase
  getFieldIdCase() {
    return FieldIdCase.forNumber(
        fieldIdCase_);
  }

  private int statsCase_ = 0;
  private Object stats_;
  public enum StatsCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    NUM_STATS(3),
    STRING_STATS(4),
    BYTES_STATS(5),
    STRUCT_STATS(7),
    STATS_NOT_SET(0);
    private final int value;
    private StatsCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static StatsCase valueOf(int value) {
      return forNumber(value);
    }

    public static StatsCase forNumber(int value) {
      switch (value) {
        case 3: return NUM_STATS;
        case 4: return STRING_STATS;
        case 5: return BYTES_STATS;
        case 7: return STRUCT_STATS;
        case 0: return STATS_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public StatsCase
  getStatsCase() {
    return StatsCase.forNumber(
        statsCase_);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  /**
   * <pre>
   * The feature name
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return Whether the name field is set.
   */
  public boolean hasName() {
    return fieldIdCase_ == 1;
  }
  /**
   * <pre>
   * The feature name
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  public String getName() {
    Object ref = "";
    if (fieldIdCase_ == 1) {
      ref = fieldId_;
    }
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (fieldIdCase_ == 1) {
        fieldId_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * The feature name
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    Object ref = "";
    if (fieldIdCase_ == 1) {
      ref = fieldId_;
    }
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      if (fieldIdCase_ == 1) {
        fieldId_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PATH_FIELD_NUMBER = 8;
  /**
   * <pre>
   * The path of the feature.
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.Path path = 8;</code>
   * @return Whether the path field is set.
   */
  @Override
  public boolean hasPath() {
    return fieldIdCase_ == 8;
  }
  /**
   * <pre>
   * The path of the feature.
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.Path path = 8;</code>
   * @return The path.
   */
  @Override
  public Path getPath() {
    if (fieldIdCase_ == 8) {
       return (Path) fieldId_;
    }
    return Path.getDefaultInstance();
  }
  /**
   * <pre>
   * The path of the feature.
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.Path path = 8;</code>
   */
  @Override
  public PathOrBuilder getPathOrBuilder() {
    if (fieldIdCase_ == 8) {
       return (Path) fieldId_;
    }
    return Path.getDefaultInstance();
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private int type_;
  /**
   * <pre>
   * The data type of the feature
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.FeatureNameStatistics.Type type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  @Override public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * The data type of the feature
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.FeatureNameStatistics.Type type = 2;</code>
   * @return The type.
   */
  @Override public Type getType() {
    @SuppressWarnings("deprecation")
    Type result = Type.valueOf(type_);
    return result == null ? Type.UNRECOGNIZED : result;
  }

  public static final int NUM_STATS_FIELD_NUMBER = 3;
  /**
   * <code>.tensorflow.metadata.v0.NumericStatistics num_stats = 3;</code>
   * @return Whether the numStats field is set.
   */
  @Override
  public boolean hasNumStats() {
    return statsCase_ == 3;
  }
  /**
   * <code>.tensorflow.metadata.v0.NumericStatistics num_stats = 3;</code>
   * @return The numStats.
   */
  @Override
  public NumericStatistics getNumStats() {
    if (statsCase_ == 3) {
       return (NumericStatistics) stats_;
    }
    return NumericStatistics.getDefaultInstance();
  }
  /**
   * <code>.tensorflow.metadata.v0.NumericStatistics num_stats = 3;</code>
   */
  @Override
  public NumericStatisticsOrBuilder getNumStatsOrBuilder() {
    if (statsCase_ == 3) {
       return (NumericStatistics) stats_;
    }
    return NumericStatistics.getDefaultInstance();
  }

  public static final int STRING_STATS_FIELD_NUMBER = 4;
  /**
   * <code>.tensorflow.metadata.v0.StringStatistics string_stats = 4;</code>
   * @return Whether the stringStats field is set.
   */
  @Override
  public boolean hasStringStats() {
    return statsCase_ == 4;
  }
  /**
   * <code>.tensorflow.metadata.v0.StringStatistics string_stats = 4;</code>
   * @return The stringStats.
   */
  @Override
  public StringStatistics getStringStats() {
    if (statsCase_ == 4) {
       return (StringStatistics) stats_;
    }
    return StringStatistics.getDefaultInstance();
  }
  /**
   * <code>.tensorflow.metadata.v0.StringStatistics string_stats = 4;</code>
   */
  @Override
  public StringStatisticsOrBuilder getStringStatsOrBuilder() {
    if (statsCase_ == 4) {
       return (StringStatistics) stats_;
    }
    return StringStatistics.getDefaultInstance();
  }

  public static final int BYTES_STATS_FIELD_NUMBER = 5;
  /**
   * <code>.tensorflow.metadata.v0.BytesStatistics bytes_stats = 5;</code>
   * @return Whether the bytesStats field is set.
   */
  @Override
  public boolean hasBytesStats() {
    return statsCase_ == 5;
  }
  /**
   * <code>.tensorflow.metadata.v0.BytesStatistics bytes_stats = 5;</code>
   * @return The bytesStats.
   */
  @Override
  public BytesStatistics getBytesStats() {
    if (statsCase_ == 5) {
       return (BytesStatistics) stats_;
    }
    return BytesStatistics.getDefaultInstance();
  }
  /**
   * <code>.tensorflow.metadata.v0.BytesStatistics bytes_stats = 5;</code>
   */
  @Override
  public BytesStatisticsOrBuilder getBytesStatsOrBuilder() {
    if (statsCase_ == 5) {
       return (BytesStatistics) stats_;
    }
    return BytesStatistics.getDefaultInstance();
  }

  public static final int STRUCT_STATS_FIELD_NUMBER = 7;
  /**
   * <code>.tensorflow.metadata.v0.StructStatistics struct_stats = 7;</code>
   * @return Whether the structStats field is set.
   */
  @Override
  public boolean hasStructStats() {
    return statsCase_ == 7;
  }
  /**
   * <code>.tensorflow.metadata.v0.StructStatistics struct_stats = 7;</code>
   * @return The structStats.
   */
  @Override
  public StructStatistics getStructStats() {
    if (statsCase_ == 7) {
       return (StructStatistics) stats_;
    }
    return StructStatistics.getDefaultInstance();
  }
  /**
   * <code>.tensorflow.metadata.v0.StructStatistics struct_stats = 7;</code>
   */
  @Override
  public StructStatisticsOrBuilder getStructStatsOrBuilder() {
    if (statsCase_ == 7) {
       return (StructStatistics) stats_;
    }
    return StructStatistics.getDefaultInstance();
  }

  public static final int CUSTOM_STATS_FIELD_NUMBER = 6;
  private java.util.List<CustomStatistic> customStats_;
  /**
   * <pre>
   * Any custom statistics can be stored in this list.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
   */
  @Override
  public java.util.List<CustomStatistic> getCustomStatsList() {
    return customStats_;
  }
  /**
   * <pre>
   * Any custom statistics can be stored in this list.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
   */
  @Override
  public java.util.List<? extends CustomStatisticOrBuilder>
      getCustomStatsOrBuilderList() {
    return customStats_;
  }
  /**
   * <pre>
   * Any custom statistics can be stored in this list.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
   */
  @Override
  public int getCustomStatsCount() {
    return customStats_.size();
  }
  /**
   * <pre>
   * Any custom statistics can be stored in this list.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
   */
  @Override
  public CustomStatistic getCustomStats(int index) {
    return customStats_.get(index);
  }
  /**
   * <pre>
   * Any custom statistics can be stored in this list.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
   */
  @Override
  public CustomStatisticOrBuilder getCustomStatsOrBuilder(
      int index) {
    return customStats_.get(index);
  }

  public static final int VALIDATION_DERIVED_SOURCE_FIELD_NUMBER = 10;
  private DerivedFeatureSource validationDerivedSource_;
  /**
   * <pre>
   * If set, indicates that that this feature is derived for validation, and
   * stores metadata about its source.
   * Experimental and subject to change.
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.DerivedFeatureSource validation_derived_source = 10;</code>
   * @return Whether the validationDerivedSource field is set.
   */
  @Override
  public boolean hasValidationDerivedSource() {
    return validationDerivedSource_ != null;
  }
  /**
   * <pre>
   * If set, indicates that that this feature is derived for validation, and
   * stores metadata about its source.
   * Experimental and subject to change.
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.DerivedFeatureSource validation_derived_source = 10;</code>
   * @return The validationDerivedSource.
   */
  @Override
  public DerivedFeatureSource getValidationDerivedSource() {
    return validationDerivedSource_ == null ? DerivedFeatureSource.getDefaultInstance() : validationDerivedSource_;
  }
  /**
   * <pre>
   * If set, indicates that that this feature is derived for validation, and
   * stores metadata about its source.
   * Experimental and subject to change.
   * </pre>
   *
   * <code>.tensorflow.metadata.v0.DerivedFeatureSource validation_derived_source = 10;</code>
   */
  @Override
  public DerivedFeatureSourceOrBuilder getValidationDerivedSourceOrBuilder() {
    return getValidationDerivedSource();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (fieldIdCase_ == 1) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fieldId_);
    }
    if (type_ != Type.INT.getNumber()) {
      output.writeEnum(2, type_);
    }
    if (statsCase_ == 3) {
      output.writeMessage(3, (NumericStatistics) stats_);
    }
    if (statsCase_ == 4) {
      output.writeMessage(4, (StringStatistics) stats_);
    }
    if (statsCase_ == 5) {
      output.writeMessage(5, (BytesStatistics) stats_);
    }
    for (int i = 0; i < customStats_.size(); i++) {
      output.writeMessage(6, customStats_.get(i));
    }
    if (statsCase_ == 7) {
      output.writeMessage(7, (StructStatistics) stats_);
    }
    if (fieldIdCase_ == 8) {
      output.writeMessage(8, (Path) fieldId_);
    }
    if (validationDerivedSource_ != null) {
      output.writeMessage(10, getValidationDerivedSource());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (fieldIdCase_ == 1) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fieldId_);
    }
    if (type_ != Type.INT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, type_);
    }
    if (statsCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (NumericStatistics) stats_);
    }
    if (statsCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (StringStatistics) stats_);
    }
    if (statsCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (BytesStatistics) stats_);
    }
    for (int i = 0; i < customStats_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, customStats_.get(i));
    }
    if (statsCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (StructStatistics) stats_);
    }
    if (fieldIdCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (Path) fieldId_);
    }
    if (validationDerivedSource_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getValidationDerivedSource());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof FeatureNameStatistics)) {
      return super.equals(obj);
    }
    FeatureNameStatistics other = (FeatureNameStatistics) obj;

    if (type_ != other.type_) return false;
    if (!getCustomStatsList()
        .equals(other.getCustomStatsList())) return false;
    if (hasValidationDerivedSource() != other.hasValidationDerivedSource()) return false;
    if (hasValidationDerivedSource()) {
      if (!getValidationDerivedSource()
          .equals(other.getValidationDerivedSource())) return false;
    }
    if (!getFieldIdCase().equals(other.getFieldIdCase())) return false;
    switch (fieldIdCase_) {
      case 1:
        if (!getName()
            .equals(other.getName())) return false;
        break;
      case 8:
        if (!getPath()
            .equals(other.getPath())) return false;
        break;
      case 0:
      default:
    }
    if (!getStatsCase().equals(other.getStatsCase())) return false;
    switch (statsCase_) {
      case 3:
        if (!getNumStats()
            .equals(other.getNumStats())) return false;
        break;
      case 4:
        if (!getStringStats()
            .equals(other.getStringStats())) return false;
        break;
      case 5:
        if (!getBytesStats()
            .equals(other.getBytesStats())) return false;
        break;
      case 7:
        if (!getStructStats()
            .equals(other.getStructStats())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    if (getCustomStatsCount() > 0) {
      hash = (37 * hash) + CUSTOM_STATS_FIELD_NUMBER;
      hash = (53 * hash) + getCustomStatsList().hashCode();
    }
    if (hasValidationDerivedSource()) {
      hash = (37 * hash) + VALIDATION_DERIVED_SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getValidationDerivedSource().hashCode();
    }
    switch (fieldIdCase_) {
      case 1:
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        break;
      case 8:
        hash = (37 * hash) + PATH_FIELD_NUMBER;
        hash = (53 * hash) + getPath().hashCode();
        break;
      case 0:
      default:
    }
    switch (statsCase_) {
      case 3:
        hash = (37 * hash) + NUM_STATS_FIELD_NUMBER;
        hash = (53 * hash) + getNumStats().hashCode();
        break;
      case 4:
        hash = (37 * hash) + STRING_STATS_FIELD_NUMBER;
        hash = (53 * hash) + getStringStats().hashCode();
        break;
      case 5:
        hash = (37 * hash) + BYTES_STATS_FIELD_NUMBER;
        hash = (53 * hash) + getBytesStats().hashCode();
        break;
      case 7:
        hash = (37 * hash) + STRUCT_STATS_FIELD_NUMBER;
        hash = (53 * hash) + getStructStats().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static FeatureNameStatistics parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FeatureNameStatistics parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FeatureNameStatistics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FeatureNameStatistics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FeatureNameStatistics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FeatureNameStatistics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FeatureNameStatistics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FeatureNameStatistics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static FeatureNameStatistics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static FeatureNameStatistics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static FeatureNameStatistics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FeatureNameStatistics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(FeatureNameStatistics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The complete set of statistics for a given feature name for a dataset.
   * NextID: 11
   * </pre>
   *
   * Protobuf type {@code tensorflow.metadata.v0.FeatureNameStatistics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.metadata.v0.FeatureNameStatistics)
      FeatureNameStatisticsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Statistics.internal_static_tensorflow_metadata_v0_FeatureNameStatistics_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Statistics.internal_static_tensorflow_metadata_v0_FeatureNameStatistics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FeatureNameStatistics.class, Builder.class);
    }

    // Construct using org.tensorflow.metadata.v0.FeatureNameStatistics.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCustomStatsFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      if (customStatsBuilder_ == null) {
        customStats_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        customStatsBuilder_.clear();
      }
      if (validationDerivedSourceBuilder_ == null) {
        validationDerivedSource_ = null;
      } else {
        validationDerivedSource_ = null;
        validationDerivedSourceBuilder_ = null;
      }
      fieldIdCase_ = 0;
      fieldId_ = null;
      statsCase_ = 0;
      stats_ = null;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Statistics.internal_static_tensorflow_metadata_v0_FeatureNameStatistics_descriptor;
    }

    @Override
    public FeatureNameStatistics getDefaultInstanceForType() {
      return FeatureNameStatistics.getDefaultInstance();
    }

    @Override
    public FeatureNameStatistics build() {
      FeatureNameStatistics result = buildPartial();
      if (!result.isInitialized()) {
        throw Builder.newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public FeatureNameStatistics buildPartial() {
      FeatureNameStatistics result = new FeatureNameStatistics(this);
      int from_bitField0_ = bitField0_;
      if (fieldIdCase_ == 1) {
        result.fieldId_ = fieldId_;
      }
      if (fieldIdCase_ == 8) {
        if (pathBuilder_ == null) {
          result.fieldId_ = fieldId_;
        } else {
          result.fieldId_ = pathBuilder_.build();
        }
      }
      result.type_ = type_;
      if (statsCase_ == 3) {
        if (numStatsBuilder_ == null) {
          result.stats_ = stats_;
        } else {
          result.stats_ = numStatsBuilder_.build();
        }
      }
      if (statsCase_ == 4) {
        if (stringStatsBuilder_ == null) {
          result.stats_ = stats_;
        } else {
          result.stats_ = stringStatsBuilder_.build();
        }
      }
      if (statsCase_ == 5) {
        if (bytesStatsBuilder_ == null) {
          result.stats_ = stats_;
        } else {
          result.stats_ = bytesStatsBuilder_.build();
        }
      }
      if (statsCase_ == 7) {
        if (structStatsBuilder_ == null) {
          result.stats_ = stats_;
        } else {
          result.stats_ = structStatsBuilder_.build();
        }
      }
      if (customStatsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          customStats_ = java.util.Collections.unmodifiableList(customStats_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.customStats_ = customStats_;
      } else {
        result.customStats_ = customStatsBuilder_.build();
      }
      if (validationDerivedSourceBuilder_ == null) {
        result.validationDerivedSource_ = validationDerivedSource_;
      } else {
        result.validationDerivedSource_ = validationDerivedSourceBuilder_.build();
      }
      result.fieldIdCase_ = fieldIdCase_;
      result.statsCase_ = statsCase_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof FeatureNameStatistics) {
        return mergeFrom((FeatureNameStatistics)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(FeatureNameStatistics other) {
      if (other == FeatureNameStatistics.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (customStatsBuilder_ == null) {
        if (!other.customStats_.isEmpty()) {
          if (customStats_.isEmpty()) {
            customStats_ = other.customStats_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCustomStatsIsMutable();
            customStats_.addAll(other.customStats_);
          }
          onChanged();
        }
      } else {
        if (!other.customStats_.isEmpty()) {
          if (customStatsBuilder_.isEmpty()) {
            customStatsBuilder_.dispose();
            customStatsBuilder_ = null;
            customStats_ = other.customStats_;
            bitField0_ = (bitField0_ & ~0x00000001);
            customStatsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCustomStatsFieldBuilder() : null;
          } else {
            customStatsBuilder_.addAllMessages(other.customStats_);
          }
        }
      }
      if (other.hasValidationDerivedSource()) {
        mergeValidationDerivedSource(other.getValidationDerivedSource());
      }
      switch (other.getFieldIdCase()) {
        case NAME: {
          fieldIdCase_ = 1;
          fieldId_ = other.fieldId_;
          onChanged();
          break;
        }
        case PATH: {
          mergePath(other.getPath());
          break;
        }
        case FIELDID_NOT_SET: {
          break;
        }
      }
      switch (other.getStatsCase()) {
        case NUM_STATS: {
          mergeNumStats(other.getNumStats());
          break;
        }
        case STRING_STATS: {
          mergeStringStats(other.getStringStats());
          break;
        }
        case BYTES_STATS: {
          mergeBytesStats(other.getBytesStats());
          break;
        }
        case STRUCT_STATS: {
          mergeStructStats(other.getStructStats());
          break;
        }
        case STATS_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      FeatureNameStatistics parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (FeatureNameStatistics) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int fieldIdCase_ = 0;
    private Object fieldId_;
    public FieldIdCase
        getFieldIdCase() {
      return FieldIdCase.forNumber(
          fieldIdCase_);
    }

    public Builder clearFieldId() {
      fieldIdCase_ = 0;
      fieldId_ = null;
      onChanged();
      return this;
    }

    private int statsCase_ = 0;
    private Object stats_;
    public StatsCase
        getStatsCase() {
      return StatsCase.forNumber(
          statsCase_);
    }

    public Builder clearStats() {
      statsCase_ = 0;
      stats_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    /**
     * <pre>
     * The feature name
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return Whether the name field is set.
     */
    @Override
    public boolean hasName() {
      return fieldIdCase_ == 1;
    }
    /**
     * <pre>
     * The feature name
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = "";
      if (fieldIdCase_ == 1) {
        ref = fieldId_;
      }
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (fieldIdCase_ == 1) {
          fieldId_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * The feature name
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = "";
      if (fieldIdCase_ == 1) {
        ref = fieldId_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        if (fieldIdCase_ == 1) {
          fieldId_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The feature name
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  fieldIdCase_ = 1;
      fieldId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The feature name
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      if (fieldIdCase_ == 1) {
        fieldIdCase_ = 0;
        fieldId_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The feature name
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  AbstractMessageLite.checkByteStringIsUtf8(value);
      fieldIdCase_ = 1;
      fieldId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        Path, Path.Builder, PathOrBuilder> pathBuilder_;
    /**
     * <pre>
     * The path of the feature.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path = 8;</code>
     * @return Whether the path field is set.
     */
    @Override
    public boolean hasPath() {
      return fieldIdCase_ == 8;
    }
    /**
     * <pre>
     * The path of the feature.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path = 8;</code>
     * @return The path.
     */
    @Override
    public Path getPath() {
      if (pathBuilder_ == null) {
        if (fieldIdCase_ == 8) {
          return (Path) fieldId_;
        }
        return Path.getDefaultInstance();
      } else {
        if (fieldIdCase_ == 8) {
          return pathBuilder_.getMessage();
        }
        return Path.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * The path of the feature.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path = 8;</code>
     */
    public Builder setPath(Path value) {
      if (pathBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fieldId_ = value;
        onChanged();
      } else {
        pathBuilder_.setMessage(value);
      }
      fieldIdCase_ = 8;
      return this;
    }
    /**
     * <pre>
     * The path of the feature.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path = 8;</code>
     */
    public Builder setPath(
        Path.Builder builderForValue) {
      if (pathBuilder_ == null) {
        fieldId_ = builderForValue.build();
        onChanged();
      } else {
        pathBuilder_.setMessage(builderForValue.build());
      }
      fieldIdCase_ = 8;
      return this;
    }
    /**
     * <pre>
     * The path of the feature.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path = 8;</code>
     */
    public Builder mergePath(Path value) {
      if (pathBuilder_ == null) {
        if (fieldIdCase_ == 8 &&
            fieldId_ != Path.getDefaultInstance()) {
          fieldId_ = Path.newBuilder((Path) fieldId_)
              .mergeFrom(value).buildPartial();
        } else {
          fieldId_ = value;
        }
        onChanged();
      } else {
        if (fieldIdCase_ == 8) {
          pathBuilder_.mergeFrom(value);
        } else {
          pathBuilder_.setMessage(value);
        }
      }
      fieldIdCase_ = 8;
      return this;
    }
    /**
     * <pre>
     * The path of the feature.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path = 8;</code>
     */
    public Builder clearPath() {
      if (pathBuilder_ == null) {
        if (fieldIdCase_ == 8) {
          fieldIdCase_ = 0;
          fieldId_ = null;
          onChanged();
        }
      } else {
        if (fieldIdCase_ == 8) {
          fieldIdCase_ = 0;
          fieldId_ = null;
        }
        pathBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The path of the feature.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path = 8;</code>
     */
    public Path.Builder getPathBuilder() {
      return getPathFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The path of the feature.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path = 8;</code>
     */
    @Override
    public PathOrBuilder getPathOrBuilder() {
      if ((fieldIdCase_ == 8) && (pathBuilder_ != null)) {
        return pathBuilder_.getMessageOrBuilder();
      } else {
        if (fieldIdCase_ == 8) {
          return (Path) fieldId_;
        }
        return Path.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * The path of the feature.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.Path path = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Path, Path.Builder, PathOrBuilder>
        getPathFieldBuilder() {
      if (pathBuilder_ == null) {
        if (!(fieldIdCase_ == 8)) {
          fieldId_ = Path.getDefaultInstance();
        }
        pathBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Path, Path.Builder, PathOrBuilder>(
                (Path) fieldId_,
                getParentForChildren(),
                isClean());
        fieldId_ = null;
      }
      fieldIdCase_ = 8;
      onChanged();;
      return pathBuilder_;
    }

    private int type_ = 0;
    /**
     * <pre>
     * The data type of the feature
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.FeatureNameStatistics.Type type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * The data type of the feature
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.FeatureNameStatistics.Type type = 2;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The data type of the feature
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.FeatureNameStatistics.Type type = 2;</code>
     * @return The type.
     */
    @Override
    public Type getType() {
      @SuppressWarnings("deprecation")
      Type result = Type.valueOf(type_);
      return result == null ? Type.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The data type of the feature
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.FeatureNameStatistics.Type type = 2;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The data type of the feature
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.FeatureNameStatistics.Type type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        NumericStatistics, NumericStatistics.Builder, NumericStatisticsOrBuilder> numStatsBuilder_;
    /**
     * <code>.tensorflow.metadata.v0.NumericStatistics num_stats = 3;</code>
     * @return Whether the numStats field is set.
     */
    @Override
    public boolean hasNumStats() {
      return statsCase_ == 3;
    }
    /**
     * <code>.tensorflow.metadata.v0.NumericStatistics num_stats = 3;</code>
     * @return The numStats.
     */
    @Override
    public NumericStatistics getNumStats() {
      if (numStatsBuilder_ == null) {
        if (statsCase_ == 3) {
          return (NumericStatistics) stats_;
        }
        return NumericStatistics.getDefaultInstance();
      } else {
        if (statsCase_ == 3) {
          return numStatsBuilder_.getMessage();
        }
        return NumericStatistics.getDefaultInstance();
      }
    }
    /**
     * <code>.tensorflow.metadata.v0.NumericStatistics num_stats = 3;</code>
     */
    public Builder setNumStats(NumericStatistics value) {
      if (numStatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        stats_ = value;
        onChanged();
      } else {
        numStatsBuilder_.setMessage(value);
      }
      statsCase_ = 3;
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.NumericStatistics num_stats = 3;</code>
     */
    public Builder setNumStats(
        NumericStatistics.Builder builderForValue) {
      if (numStatsBuilder_ == null) {
        stats_ = builderForValue.build();
        onChanged();
      } else {
        numStatsBuilder_.setMessage(builderForValue.build());
      }
      statsCase_ = 3;
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.NumericStatistics num_stats = 3;</code>
     */
    public Builder mergeNumStats(NumericStatistics value) {
      if (numStatsBuilder_ == null) {
        if (statsCase_ == 3 &&
            stats_ != NumericStatistics.getDefaultInstance()) {
          stats_ = NumericStatistics.newBuilder((NumericStatistics) stats_)
              .mergeFrom(value).buildPartial();
        } else {
          stats_ = value;
        }
        onChanged();
      } else {
        if (statsCase_ == 3) {
          numStatsBuilder_.mergeFrom(value);
        } else {
          numStatsBuilder_.setMessage(value);
        }
      }
      statsCase_ = 3;
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.NumericStatistics num_stats = 3;</code>
     */
    public Builder clearNumStats() {
      if (numStatsBuilder_ == null) {
        if (statsCase_ == 3) {
          statsCase_ = 0;
          stats_ = null;
          onChanged();
        }
      } else {
        if (statsCase_ == 3) {
          statsCase_ = 0;
          stats_ = null;
        }
        numStatsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.NumericStatistics num_stats = 3;</code>
     */
    public NumericStatistics.Builder getNumStatsBuilder() {
      return getNumStatsFieldBuilder().getBuilder();
    }
    /**
     * <code>.tensorflow.metadata.v0.NumericStatistics num_stats = 3;</code>
     */
    @Override
    public NumericStatisticsOrBuilder getNumStatsOrBuilder() {
      if ((statsCase_ == 3) && (numStatsBuilder_ != null)) {
        return numStatsBuilder_.getMessageOrBuilder();
      } else {
        if (statsCase_ == 3) {
          return (NumericStatistics) stats_;
        }
        return NumericStatistics.getDefaultInstance();
      }
    }
    /**
     * <code>.tensorflow.metadata.v0.NumericStatistics num_stats = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        NumericStatistics, NumericStatistics.Builder, NumericStatisticsOrBuilder>
        getNumStatsFieldBuilder() {
      if (numStatsBuilder_ == null) {
        if (!(statsCase_ == 3)) {
          stats_ = NumericStatistics.getDefaultInstance();
        }
        numStatsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            NumericStatistics, NumericStatistics.Builder, NumericStatisticsOrBuilder>(
                (NumericStatistics) stats_,
                getParentForChildren(),
                isClean());
        stats_ = null;
      }
      statsCase_ = 3;
      onChanged();;
      return numStatsBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        StringStatistics, StringStatistics.Builder, StringStatisticsOrBuilder> stringStatsBuilder_;
    /**
     * <code>.tensorflow.metadata.v0.StringStatistics string_stats = 4;</code>
     * @return Whether the stringStats field is set.
     */
    @Override
    public boolean hasStringStats() {
      return statsCase_ == 4;
    }
    /**
     * <code>.tensorflow.metadata.v0.StringStatistics string_stats = 4;</code>
     * @return The stringStats.
     */
    @Override
    public StringStatistics getStringStats() {
      if (stringStatsBuilder_ == null) {
        if (statsCase_ == 4) {
          return (StringStatistics) stats_;
        }
        return StringStatistics.getDefaultInstance();
      } else {
        if (statsCase_ == 4) {
          return stringStatsBuilder_.getMessage();
        }
        return StringStatistics.getDefaultInstance();
      }
    }
    /**
     * <code>.tensorflow.metadata.v0.StringStatistics string_stats = 4;</code>
     */
    public Builder setStringStats(StringStatistics value) {
      if (stringStatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        stats_ = value;
        onChanged();
      } else {
        stringStatsBuilder_.setMessage(value);
      }
      statsCase_ = 4;
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.StringStatistics string_stats = 4;</code>
     */
    public Builder setStringStats(
        StringStatistics.Builder builderForValue) {
      if (stringStatsBuilder_ == null) {
        stats_ = builderForValue.build();
        onChanged();
      } else {
        stringStatsBuilder_.setMessage(builderForValue.build());
      }
      statsCase_ = 4;
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.StringStatistics string_stats = 4;</code>
     */
    public Builder mergeStringStats(StringStatistics value) {
      if (stringStatsBuilder_ == null) {
        if (statsCase_ == 4 &&
            stats_ != StringStatistics.getDefaultInstance()) {
          stats_ = StringStatistics.newBuilder((StringStatistics) stats_)
              .mergeFrom(value).buildPartial();
        } else {
          stats_ = value;
        }
        onChanged();
      } else {
        if (statsCase_ == 4) {
          stringStatsBuilder_.mergeFrom(value);
        } else {
          stringStatsBuilder_.setMessage(value);
        }
      }
      statsCase_ = 4;
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.StringStatistics string_stats = 4;</code>
     */
    public Builder clearStringStats() {
      if (stringStatsBuilder_ == null) {
        if (statsCase_ == 4) {
          statsCase_ = 0;
          stats_ = null;
          onChanged();
        }
      } else {
        if (statsCase_ == 4) {
          statsCase_ = 0;
          stats_ = null;
        }
        stringStatsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.StringStatistics string_stats = 4;</code>
     */
    public StringStatistics.Builder getStringStatsBuilder() {
      return getStringStatsFieldBuilder().getBuilder();
    }
    /**
     * <code>.tensorflow.metadata.v0.StringStatistics string_stats = 4;</code>
     */
    @Override
    public StringStatisticsOrBuilder getStringStatsOrBuilder() {
      if ((statsCase_ == 4) && (stringStatsBuilder_ != null)) {
        return stringStatsBuilder_.getMessageOrBuilder();
      } else {
        if (statsCase_ == 4) {
          return (StringStatistics) stats_;
        }
        return StringStatistics.getDefaultInstance();
      }
    }
    /**
     * <code>.tensorflow.metadata.v0.StringStatistics string_stats = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        StringStatistics, StringStatistics.Builder, StringStatisticsOrBuilder>
        getStringStatsFieldBuilder() {
      if (stringStatsBuilder_ == null) {
        if (!(statsCase_ == 4)) {
          stats_ = StringStatistics.getDefaultInstance();
        }
        stringStatsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            StringStatistics, StringStatistics.Builder, StringStatisticsOrBuilder>(
                (StringStatistics) stats_,
                getParentForChildren(),
                isClean());
        stats_ = null;
      }
      statsCase_ = 4;
      onChanged();;
      return stringStatsBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        BytesStatistics, BytesStatistics.Builder, BytesStatisticsOrBuilder> bytesStatsBuilder_;
    /**
     * <code>.tensorflow.metadata.v0.BytesStatistics bytes_stats = 5;</code>
     * @return Whether the bytesStats field is set.
     */
    @Override
    public boolean hasBytesStats() {
      return statsCase_ == 5;
    }
    /**
     * <code>.tensorflow.metadata.v0.BytesStatistics bytes_stats = 5;</code>
     * @return The bytesStats.
     */
    @Override
    public BytesStatistics getBytesStats() {
      if (bytesStatsBuilder_ == null) {
        if (statsCase_ == 5) {
          return (BytesStatistics) stats_;
        }
        return BytesStatistics.getDefaultInstance();
      } else {
        if (statsCase_ == 5) {
          return bytesStatsBuilder_.getMessage();
        }
        return BytesStatistics.getDefaultInstance();
      }
    }
    /**
     * <code>.tensorflow.metadata.v0.BytesStatistics bytes_stats = 5;</code>
     */
    public Builder setBytesStats(BytesStatistics value) {
      if (bytesStatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        stats_ = value;
        onChanged();
      } else {
        bytesStatsBuilder_.setMessage(value);
      }
      statsCase_ = 5;
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.BytesStatistics bytes_stats = 5;</code>
     */
    public Builder setBytesStats(
        BytesStatistics.Builder builderForValue) {
      if (bytesStatsBuilder_ == null) {
        stats_ = builderForValue.build();
        onChanged();
      } else {
        bytesStatsBuilder_.setMessage(builderForValue.build());
      }
      statsCase_ = 5;
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.BytesStatistics bytes_stats = 5;</code>
     */
    public Builder mergeBytesStats(BytesStatistics value) {
      if (bytesStatsBuilder_ == null) {
        if (statsCase_ == 5 &&
            stats_ != BytesStatistics.getDefaultInstance()) {
          stats_ = BytesStatistics.newBuilder((BytesStatistics) stats_)
              .mergeFrom(value).buildPartial();
        } else {
          stats_ = value;
        }
        onChanged();
      } else {
        if (statsCase_ == 5) {
          bytesStatsBuilder_.mergeFrom(value);
        } else {
          bytesStatsBuilder_.setMessage(value);
        }
      }
      statsCase_ = 5;
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.BytesStatistics bytes_stats = 5;</code>
     */
    public Builder clearBytesStats() {
      if (bytesStatsBuilder_ == null) {
        if (statsCase_ == 5) {
          statsCase_ = 0;
          stats_ = null;
          onChanged();
        }
      } else {
        if (statsCase_ == 5) {
          statsCase_ = 0;
          stats_ = null;
        }
        bytesStatsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.BytesStatistics bytes_stats = 5;</code>
     */
    public BytesStatistics.Builder getBytesStatsBuilder() {
      return getBytesStatsFieldBuilder().getBuilder();
    }
    /**
     * <code>.tensorflow.metadata.v0.BytesStatistics bytes_stats = 5;</code>
     */
    @Override
    public BytesStatisticsOrBuilder getBytesStatsOrBuilder() {
      if ((statsCase_ == 5) && (bytesStatsBuilder_ != null)) {
        return bytesStatsBuilder_.getMessageOrBuilder();
      } else {
        if (statsCase_ == 5) {
          return (BytesStatistics) stats_;
        }
        return BytesStatistics.getDefaultInstance();
      }
    }
    /**
     * <code>.tensorflow.metadata.v0.BytesStatistics bytes_stats = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        BytesStatistics, BytesStatistics.Builder, BytesStatisticsOrBuilder>
        getBytesStatsFieldBuilder() {
      if (bytesStatsBuilder_ == null) {
        if (!(statsCase_ == 5)) {
          stats_ = BytesStatistics.getDefaultInstance();
        }
        bytesStatsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            BytesStatistics, BytesStatistics.Builder, BytesStatisticsOrBuilder>(
                (BytesStatistics) stats_,
                getParentForChildren(),
                isClean());
        stats_ = null;
      }
      statsCase_ = 5;
      onChanged();;
      return bytesStatsBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        StructStatistics, StructStatistics.Builder, StructStatisticsOrBuilder> structStatsBuilder_;
    /**
     * <code>.tensorflow.metadata.v0.StructStatistics struct_stats = 7;</code>
     * @return Whether the structStats field is set.
     */
    @Override
    public boolean hasStructStats() {
      return statsCase_ == 7;
    }
    /**
     * <code>.tensorflow.metadata.v0.StructStatistics struct_stats = 7;</code>
     * @return The structStats.
     */
    @Override
    public StructStatistics getStructStats() {
      if (structStatsBuilder_ == null) {
        if (statsCase_ == 7) {
          return (StructStatistics) stats_;
        }
        return StructStatistics.getDefaultInstance();
      } else {
        if (statsCase_ == 7) {
          return structStatsBuilder_.getMessage();
        }
        return StructStatistics.getDefaultInstance();
      }
    }
    /**
     * <code>.tensorflow.metadata.v0.StructStatistics struct_stats = 7;</code>
     */
    public Builder setStructStats(StructStatistics value) {
      if (structStatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        stats_ = value;
        onChanged();
      } else {
        structStatsBuilder_.setMessage(value);
      }
      statsCase_ = 7;
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.StructStatistics struct_stats = 7;</code>
     */
    public Builder setStructStats(
        StructStatistics.Builder builderForValue) {
      if (structStatsBuilder_ == null) {
        stats_ = builderForValue.build();
        onChanged();
      } else {
        structStatsBuilder_.setMessage(builderForValue.build());
      }
      statsCase_ = 7;
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.StructStatistics struct_stats = 7;</code>
     */
    public Builder mergeStructStats(StructStatistics value) {
      if (structStatsBuilder_ == null) {
        if (statsCase_ == 7 &&
            stats_ != StructStatistics.getDefaultInstance()) {
          stats_ = StructStatistics.newBuilder((StructStatistics) stats_)
              .mergeFrom(value).buildPartial();
        } else {
          stats_ = value;
        }
        onChanged();
      } else {
        if (statsCase_ == 7) {
          structStatsBuilder_.mergeFrom(value);
        } else {
          structStatsBuilder_.setMessage(value);
        }
      }
      statsCase_ = 7;
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.StructStatistics struct_stats = 7;</code>
     */
    public Builder clearStructStats() {
      if (structStatsBuilder_ == null) {
        if (statsCase_ == 7) {
          statsCase_ = 0;
          stats_ = null;
          onChanged();
        }
      } else {
        if (statsCase_ == 7) {
          statsCase_ = 0;
          stats_ = null;
        }
        structStatsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.tensorflow.metadata.v0.StructStatistics struct_stats = 7;</code>
     */
    public StructStatistics.Builder getStructStatsBuilder() {
      return getStructStatsFieldBuilder().getBuilder();
    }
    /**
     * <code>.tensorflow.metadata.v0.StructStatistics struct_stats = 7;</code>
     */
    @Override
    public StructStatisticsOrBuilder getStructStatsOrBuilder() {
      if ((statsCase_ == 7) && (structStatsBuilder_ != null)) {
        return structStatsBuilder_.getMessageOrBuilder();
      } else {
        if (statsCase_ == 7) {
          return (StructStatistics) stats_;
        }
        return StructStatistics.getDefaultInstance();
      }
    }
    /**
     * <code>.tensorflow.metadata.v0.StructStatistics struct_stats = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        StructStatistics, StructStatistics.Builder, StructStatisticsOrBuilder>
        getStructStatsFieldBuilder() {
      if (structStatsBuilder_ == null) {
        if (!(statsCase_ == 7)) {
          stats_ = StructStatistics.getDefaultInstance();
        }
        structStatsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            StructStatistics, StructStatistics.Builder, StructStatisticsOrBuilder>(
                (StructStatistics) stats_,
                getParentForChildren(),
                isClean());
        stats_ = null;
      }
      statsCase_ = 7;
      onChanged();;
      return structStatsBuilder_;
    }

    private java.util.List<CustomStatistic> customStats_ =
      java.util.Collections.emptyList();
    private void ensureCustomStatsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        customStats_ = new java.util.ArrayList<CustomStatistic>(customStats_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        CustomStatistic, CustomStatistic.Builder, CustomStatisticOrBuilder> customStatsBuilder_;

    /**
     * <pre>
     * Any custom statistics can be stored in this list.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
     */
    public java.util.List<CustomStatistic> getCustomStatsList() {
      if (customStatsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(customStats_);
      } else {
        return customStatsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Any custom statistics can be stored in this list.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
     */
    public int getCustomStatsCount() {
      if (customStatsBuilder_ == null) {
        return customStats_.size();
      } else {
        return customStatsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Any custom statistics can be stored in this list.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
     */
    public CustomStatistic getCustomStats(int index) {
      if (customStatsBuilder_ == null) {
        return customStats_.get(index);
      } else {
        return customStatsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Any custom statistics can be stored in this list.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
     */
    public Builder setCustomStats(
        int index, CustomStatistic value) {
      if (customStatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCustomStatsIsMutable();
        customStats_.set(index, value);
        onChanged();
      } else {
        customStatsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Any custom statistics can be stored in this list.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
     */
    public Builder setCustomStats(
        int index, CustomStatistic.Builder builderForValue) {
      if (customStatsBuilder_ == null) {
        ensureCustomStatsIsMutable();
        customStats_.set(index, builderForValue.build());
        onChanged();
      } else {
        customStatsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Any custom statistics can be stored in this list.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
     */
    public Builder addCustomStats(CustomStatistic value) {
      if (customStatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCustomStatsIsMutable();
        customStats_.add(value);
        onChanged();
      } else {
        customStatsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Any custom statistics can be stored in this list.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
     */
    public Builder addCustomStats(
        int index, CustomStatistic value) {
      if (customStatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCustomStatsIsMutable();
        customStats_.add(index, value);
        onChanged();
      } else {
        customStatsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Any custom statistics can be stored in this list.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
     */
    public Builder addCustomStats(
        CustomStatistic.Builder builderForValue) {
      if (customStatsBuilder_ == null) {
        ensureCustomStatsIsMutable();
        customStats_.add(builderForValue.build());
        onChanged();
      } else {
        customStatsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Any custom statistics can be stored in this list.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
     */
    public Builder addCustomStats(
        int index, CustomStatistic.Builder builderForValue) {
      if (customStatsBuilder_ == null) {
        ensureCustomStatsIsMutable();
        customStats_.add(index, builderForValue.build());
        onChanged();
      } else {
        customStatsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Any custom statistics can be stored in this list.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
     */
    public Builder addAllCustomStats(
        Iterable<? extends CustomStatistic> values) {
      if (customStatsBuilder_ == null) {
        ensureCustomStatsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, customStats_);
        onChanged();
      } else {
        customStatsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Any custom statistics can be stored in this list.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
     */
    public Builder clearCustomStats() {
      if (customStatsBuilder_ == null) {
        customStats_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        customStatsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Any custom statistics can be stored in this list.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
     */
    public Builder removeCustomStats(int index) {
      if (customStatsBuilder_ == null) {
        ensureCustomStatsIsMutable();
        customStats_.remove(index);
        onChanged();
      } else {
        customStatsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Any custom statistics can be stored in this list.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
     */
    public CustomStatistic.Builder getCustomStatsBuilder(
        int index) {
      return getCustomStatsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Any custom statistics can be stored in this list.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
     */
    public CustomStatisticOrBuilder getCustomStatsOrBuilder(
        int index) {
      if (customStatsBuilder_ == null) {
        return customStats_.get(index);  } else {
        return customStatsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Any custom statistics can be stored in this list.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
     */
    public java.util.List<? extends CustomStatisticOrBuilder>
         getCustomStatsOrBuilderList() {
      if (customStatsBuilder_ != null) {
        return customStatsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(customStats_);
      }
    }
    /**
     * <pre>
     * Any custom statistics can be stored in this list.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
     */
    public CustomStatistic.Builder addCustomStatsBuilder() {
      return getCustomStatsFieldBuilder().addBuilder(
          CustomStatistic.getDefaultInstance());
    }
    /**
     * <pre>
     * Any custom statistics can be stored in this list.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
     */
    public CustomStatistic.Builder addCustomStatsBuilder(
        int index) {
      return getCustomStatsFieldBuilder().addBuilder(
          index, CustomStatistic.getDefaultInstance());
    }
    /**
     * <pre>
     * Any custom statistics can be stored in this list.
     * </pre>
     *
     * <code>repeated .tensorflow.metadata.v0.CustomStatistic custom_stats = 6;</code>
     */
    public java.util.List<CustomStatistic.Builder>
         getCustomStatsBuilderList() {
      return getCustomStatsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        CustomStatistic, CustomStatistic.Builder, CustomStatisticOrBuilder>
        getCustomStatsFieldBuilder() {
      if (customStatsBuilder_ == null) {
        customStatsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            CustomStatistic, CustomStatistic.Builder, CustomStatisticOrBuilder>(
                customStats_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        customStats_ = null;
      }
      return customStatsBuilder_;
    }

    private DerivedFeatureSource validationDerivedSource_;
    private com.google.protobuf.SingleFieldBuilderV3<
        DerivedFeatureSource, DerivedFeatureSource.Builder, DerivedFeatureSourceOrBuilder> validationDerivedSourceBuilder_;
    /**
     * <pre>
     * If set, indicates that that this feature is derived for validation, and
     * stores metadata about its source.
     * Experimental and subject to change.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.DerivedFeatureSource validation_derived_source = 10;</code>
     * @return Whether the validationDerivedSource field is set.
     */
    public boolean hasValidationDerivedSource() {
      return validationDerivedSourceBuilder_ != null || validationDerivedSource_ != null;
    }
    /**
     * <pre>
     * If set, indicates that that this feature is derived for validation, and
     * stores metadata about its source.
     * Experimental and subject to change.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.DerivedFeatureSource validation_derived_source = 10;</code>
     * @return The validationDerivedSource.
     */
    public DerivedFeatureSource getValidationDerivedSource() {
      if (validationDerivedSourceBuilder_ == null) {
        return validationDerivedSource_ == null ? DerivedFeatureSource.getDefaultInstance() : validationDerivedSource_;
      } else {
        return validationDerivedSourceBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * If set, indicates that that this feature is derived for validation, and
     * stores metadata about its source.
     * Experimental and subject to change.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.DerivedFeatureSource validation_derived_source = 10;</code>
     */
    public Builder setValidationDerivedSource(DerivedFeatureSource value) {
      if (validationDerivedSourceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        validationDerivedSource_ = value;
        onChanged();
      } else {
        validationDerivedSourceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * If set, indicates that that this feature is derived for validation, and
     * stores metadata about its source.
     * Experimental and subject to change.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.DerivedFeatureSource validation_derived_source = 10;</code>
     */
    public Builder setValidationDerivedSource(
        DerivedFeatureSource.Builder builderForValue) {
      if (validationDerivedSourceBuilder_ == null) {
        validationDerivedSource_ = builderForValue.build();
        onChanged();
      } else {
        validationDerivedSourceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * If set, indicates that that this feature is derived for validation, and
     * stores metadata about its source.
     * Experimental and subject to change.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.DerivedFeatureSource validation_derived_source = 10;</code>
     */
    public Builder mergeValidationDerivedSource(DerivedFeatureSource value) {
      if (validationDerivedSourceBuilder_ == null) {
        if (validationDerivedSource_ != null) {
          validationDerivedSource_ =
            DerivedFeatureSource.newBuilder(validationDerivedSource_).mergeFrom(value).buildPartial();
        } else {
          validationDerivedSource_ = value;
        }
        onChanged();
      } else {
        validationDerivedSourceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * If set, indicates that that this feature is derived for validation, and
     * stores metadata about its source.
     * Experimental and subject to change.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.DerivedFeatureSource validation_derived_source = 10;</code>
     */
    public Builder clearValidationDerivedSource() {
      if (validationDerivedSourceBuilder_ == null) {
        validationDerivedSource_ = null;
        onChanged();
      } else {
        validationDerivedSource_ = null;
        validationDerivedSourceBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * If set, indicates that that this feature is derived for validation, and
     * stores metadata about its source.
     * Experimental and subject to change.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.DerivedFeatureSource validation_derived_source = 10;</code>
     */
    public DerivedFeatureSource.Builder getValidationDerivedSourceBuilder() {
      
      onChanged();
      return getValidationDerivedSourceFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * If set, indicates that that this feature is derived for validation, and
     * stores metadata about its source.
     * Experimental and subject to change.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.DerivedFeatureSource validation_derived_source = 10;</code>
     */
    public DerivedFeatureSourceOrBuilder getValidationDerivedSourceOrBuilder() {
      if (validationDerivedSourceBuilder_ != null) {
        return validationDerivedSourceBuilder_.getMessageOrBuilder();
      } else {
        return validationDerivedSource_ == null ?
            DerivedFeatureSource.getDefaultInstance() : validationDerivedSource_;
      }
    }
    /**
     * <pre>
     * If set, indicates that that this feature is derived for validation, and
     * stores metadata about its source.
     * Experimental and subject to change.
     * </pre>
     *
     * <code>.tensorflow.metadata.v0.DerivedFeatureSource validation_derived_source = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        DerivedFeatureSource, DerivedFeatureSource.Builder, DerivedFeatureSourceOrBuilder>
        getValidationDerivedSourceFieldBuilder() {
      if (validationDerivedSourceBuilder_ == null) {
        validationDerivedSourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            DerivedFeatureSource, DerivedFeatureSource.Builder, DerivedFeatureSourceOrBuilder>(
                getValidationDerivedSource(),
                getParentForChildren(),
                isClean());
        validationDerivedSource_ = null;
      }
      return validationDerivedSourceBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.metadata.v0.FeatureNameStatistics)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.metadata.v0.FeatureNameStatistics)
  private static final FeatureNameStatistics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new FeatureNameStatistics();
  }

  public static FeatureNameStatistics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FeatureNameStatistics>
      PARSER = new com.google.protobuf.AbstractParser<FeatureNameStatistics>() {
    @Override
    public FeatureNameStatistics parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FeatureNameStatistics(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FeatureNameStatistics> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<FeatureNameStatistics> getParserForType() {
    return PARSER;
  }

  @Override
  public FeatureNameStatistics getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

