// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statistics.proto

package org.tensorflow.metadata.v0;

public interface RankHistogramOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.metadata.v0.RankHistogram)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A list of buckets in the histogram, sorted from lowest-ranked bucket to
   * highest-ranked bucket.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.RankHistogram.Bucket buckets = 1;</code>
   */
  java.util.List<RankHistogram.Bucket>
      getBucketsList();
  /**
   * <pre>
   * A list of buckets in the histogram, sorted from lowest-ranked bucket to
   * highest-ranked bucket.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.RankHistogram.Bucket buckets = 1;</code>
   */
  RankHistogram.Bucket getBuckets(int index);
  /**
   * <pre>
   * A list of buckets in the histogram, sorted from lowest-ranked bucket to
   * highest-ranked bucket.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.RankHistogram.Bucket buckets = 1;</code>
   */
  int getBucketsCount();
  /**
   * <pre>
   * A list of buckets in the histogram, sorted from lowest-ranked bucket to
   * highest-ranked bucket.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.RankHistogram.Bucket buckets = 1;</code>
   */
  java.util.List<? extends RankHistogram.BucketOrBuilder>
      getBucketsOrBuilderList();
  /**
   * <pre>
   * A list of buckets in the histogram, sorted from lowest-ranked bucket to
   * highest-ranked bucket.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.RankHistogram.Bucket buckets = 1;</code>
   */
  RankHistogram.BucketOrBuilder getBucketsOrBuilder(
      int index);

  /**
   * <pre>
   * An optional descriptive name of the histogram, to be used for labeling.
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  String getName();
  /**
   * <pre>
   * An optional descriptive name of the histogram, to be used for labeling.
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
