// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statistics.proto

package org.tensorflow.metadata.v0;

public interface WeightedNumericStatisticsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.metadata.v0.WeightedNumericStatistics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The weighted mean of the values
   * </pre>
   *
   * <code>double mean = 1;</code>
   * @return The mean.
   */
  double getMean();

  /**
   * <pre>
   * The weighted standard deviation of the values
   * </pre>
   *
   * <code>double std_dev = 2;</code>
   * @return The stdDev.
   */
  double getStdDev();

  /**
   * <pre>
   * The weighted median of the values
   * </pre>
   *
   * <code>double median = 3;</code>
   * @return The median.
   */
  double getMedian();

  /**
   * <pre>
   * The histogram(s) of the weighted feature values.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.Histogram histograms = 4;</code>
   */
  java.util.List<Histogram>
      getHistogramsList();
  /**
   * <pre>
   * The histogram(s) of the weighted feature values.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.Histogram histograms = 4;</code>
   */
  Histogram getHistograms(int index);
  /**
   * <pre>
   * The histogram(s) of the weighted feature values.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.Histogram histograms = 4;</code>
   */
  int getHistogramsCount();
  /**
   * <pre>
   * The histogram(s) of the weighted feature values.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.Histogram histograms = 4;</code>
   */
  java.util.List<? extends HistogramOrBuilder>
      getHistogramsOrBuilderList();
  /**
   * <pre>
   * The histogram(s) of the weighted feature values.
   * </pre>
   *
   * <code>repeated .tensorflow.metadata.v0.Histogram histograms = 4;</code>
   */
  HistogramOrBuilder getHistogramsOrBuilder(
      int index);
}
