package com.alibaba.alink.operator.local.dataproc.vector;

import org.apache.flink.ml.api.misc.param.Params;

import com.alibaba.alink.common.annotation.NameCn;
import com.alibaba.alink.common.annotation.ParamSelectColumnSpec;
import com.alibaba.alink.common.annotation.TypeCollections;
import com.alibaba.alink.operator.common.dataproc.vector.VectorAssemblerMapper;
import com.alibaba.alink.operator.local.utils.MapLocalOp;
import com.alibaba.alink.params.dataproc.vector.VectorAssemblerParams;

/**
 * VectorAssembler is a transformer that combines a given list of columns(vector or numerical column) into a single
 * vector column. It is useful for combining features generated by different feature generators into a
 * single feature vector. VectorAssembler accepts the following input column types: all numeric types, and vector type.
 * In each row, the values of the input columns will be concatenated into a vector in the specified order.
 * <p>
 * this operator can transform batch data.
 */
@ParamSelectColumnSpec(name = "selectedCol", allowedTypeCollections = TypeCollections.VECTOR_TYPES)
@NameCn("向量聚合")
public final class VectorAssemblerLocalOp extends MapLocalOp <VectorAssemblerLocalOp>
	implements VectorAssemblerParams <VectorAssemblerLocalOp> {

	public VectorAssemblerLocalOp() {
		this(null);
	}

	public VectorAssemblerLocalOp(Params params) {
		super(VectorAssemblerMapper::new, params);
	}
}
