package com.alibaba.alink.operator.batch.dataproc;

import org.apache.flink.ml.api.misc.param.Params;

import com.alibaba.alink.operator.batch.utils.ModelMapBatchOp;
import com.alibaba.alink.operator.common.dataproc.MultiStringIndexerModelMapper;
import com.alibaba.alink.params.dataproc.MultiStringIndexerPredictParams;

/**
 * Map string to index based on the model generated by {@link MultiStringIndexerTrainBatchOp}.
 */
public final class MultiStringIndexerPredictBatchOp
	extends ModelMapBatchOp<MultiStringIndexerPredictBatchOp>
	implements MultiStringIndexerPredictParams <MultiStringIndexerPredictBatchOp> {

	public MultiStringIndexerPredictBatchOp() {
		this(new Params());
	}

	public MultiStringIndexerPredictBatchOp(Params params) {
		super(MultiStringIndexerModelMapper::new, params);
	}

}
