package com.alibaba.alink.pipeline.dataproc.vector;

import org.apache.flink.ml.api.misc.param.Params;

import com.alibaba.alink.operator.common.dataproc.vector.VectorAssemblerMapper;
import com.alibaba.alink.params.dataproc.vector.VectorAssemblerParams;
import com.alibaba.alink.pipeline.MapTransformer;

/**
 * /**
 * VectorAssembler is a transformer that combines a given list of columns(vector or numerical column) into a single
 * vector column. It is useful for combining features generated by different feature generators into a
 * single feature vector. VectorAssembler accepts the following input column types: all numeric types, and vector type.
 * In each row, the values of the input columns will be concatenated into a vector in the specified order.
 *
 * this operator cam transform batch data.
 */
public class VectorAssembler extends MapTransformer<VectorAssembler>
	implements VectorAssemblerParams <VectorAssembler> {

	public VectorAssembler() {
		this(null);
	}

	public VectorAssembler(Params params) {
		super(VectorAssemblerMapper::new, params);
	}
}
