// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: easy_rec/python/protos/autoint.proto

package com.alibaba.alink.operator.batch.dl.ctr.protos;

public final class Autoint {
  private Autoint() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AutoIntOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.AutoInt)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The number of heads
     * </pre>
     *
     * <code>required uint32 multi_head_num = 1 [default = 1];</code>
     */
    boolean hasMultiHeadNum();
    /**
     * <pre>
     * The number of heads
     * </pre>
     *
     * <code>required uint32 multi_head_num = 1 [default = 1];</code>
     */
    int getMultiHeadNum();

    /**
     * <pre>
     * The dimension of heads
     * </pre>
     *
     * <code>required uint32 multi_head_size = 2;</code>
     */
    boolean hasMultiHeadSize();
    /**
     * <pre>
     * The dimension of heads
     * </pre>
     *
     * <code>required uint32 multi_head_size = 2;</code>
     */
    int getMultiHeadSize();

    /**
     * <pre>
     * The number of interacting layers
     * </pre>
     *
     * <code>required uint32 interacting_layer_num = 3 [default = 1];</code>
     */
    boolean hasInteractingLayerNum();
    /**
     * <pre>
     * The number of interacting layers
     * </pre>
     *
     * <code>required uint32 interacting_layer_num = 3 [default = 1];</code>
     */
    int getInteractingLayerNum();

    /**
     * <code>required float l2_regularization = 4 [default = 0.0001];</code>
     */
    boolean hasL2Regularization();
    /**
     * <code>required float l2_regularization = 4 [default = 0.0001];</code>
     */
    float getL2Regularization();
  }
  /**
   * Protobuf type {@code protos.AutoInt}
   */
  public  static final class AutoInt extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.AutoInt)
      AutoIntOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AutoInt.newBuilder() to construct.
    private AutoInt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AutoInt() {
      multiHeadNum_ = 1;
      interactingLayerNum_ = 1;
      l2Regularization_ = 0.0001F;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AutoInt();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AutoInt(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              multiHeadNum_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              multiHeadSize_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              interactingLayerNum_ = input.readUInt32();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              l2Regularization_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.internal_static_protos_AutoInt_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.internal_static_protos_AutoInt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt.class, com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt.Builder.class);
    }

    private int bitField0_;
    public static final int MULTI_HEAD_NUM_FIELD_NUMBER = 1;
    private int multiHeadNum_;
    /**
     * <pre>
     * The number of heads
     * </pre>
     *
     * <code>required uint32 multi_head_num = 1 [default = 1];</code>
     */
    public boolean hasMultiHeadNum() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The number of heads
     * </pre>
     *
     * <code>required uint32 multi_head_num = 1 [default = 1];</code>
     */
    public int getMultiHeadNum() {
      return multiHeadNum_;
    }

    public static final int MULTI_HEAD_SIZE_FIELD_NUMBER = 2;
    private int multiHeadSize_;
    /**
     * <pre>
     * The dimension of heads
     * </pre>
     *
     * <code>required uint32 multi_head_size = 2;</code>
     */
    public boolean hasMultiHeadSize() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The dimension of heads
     * </pre>
     *
     * <code>required uint32 multi_head_size = 2;</code>
     */
    public int getMultiHeadSize() {
      return multiHeadSize_;
    }

    public static final int INTERACTING_LAYER_NUM_FIELD_NUMBER = 3;
    private int interactingLayerNum_;
    /**
     * <pre>
     * The number of interacting layers
     * </pre>
     *
     * <code>required uint32 interacting_layer_num = 3 [default = 1];</code>
     */
    public boolean hasInteractingLayerNum() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * The number of interacting layers
     * </pre>
     *
     * <code>required uint32 interacting_layer_num = 3 [default = 1];</code>
     */
    public int getInteractingLayerNum() {
      return interactingLayerNum_;
    }

    public static final int L2_REGULARIZATION_FIELD_NUMBER = 4;
    private float l2Regularization_;
    /**
     * <code>required float l2_regularization = 4 [default = 0.0001];</code>
     */
    public boolean hasL2Regularization() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required float l2_regularization = 4 [default = 0.0001];</code>
     */
    public float getL2Regularization() {
      return l2Regularization_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMultiHeadNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMultiHeadSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInteractingLayerNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasL2Regularization()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, multiHeadNum_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt32(2, multiHeadSize_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt32(3, interactingLayerNum_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeFloat(4, l2Regularization_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, multiHeadNum_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, multiHeadSize_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, interactingLayerNum_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, l2Regularization_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt)) {
        return super.equals(obj);
      }
      com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt other = (com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt) obj;

      if (hasMultiHeadNum() != other.hasMultiHeadNum()) return false;
      if (hasMultiHeadNum()) {
        if (getMultiHeadNum()
            != other.getMultiHeadNum()) return false;
      }
      if (hasMultiHeadSize() != other.hasMultiHeadSize()) return false;
      if (hasMultiHeadSize()) {
        if (getMultiHeadSize()
            != other.getMultiHeadSize()) return false;
      }
      if (hasInteractingLayerNum() != other.hasInteractingLayerNum()) return false;
      if (hasInteractingLayerNum()) {
        if (getInteractingLayerNum()
            != other.getInteractingLayerNum()) return false;
      }
      if (hasL2Regularization() != other.hasL2Regularization()) return false;
      if (hasL2Regularization()) {
        if (java.lang.Float.floatToIntBits(getL2Regularization())
            != java.lang.Float.floatToIntBits(
                other.getL2Regularization())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMultiHeadNum()) {
        hash = (37 * hash) + MULTI_HEAD_NUM_FIELD_NUMBER;
        hash = (53 * hash) + getMultiHeadNum();
      }
      if (hasMultiHeadSize()) {
        hash = (37 * hash) + MULTI_HEAD_SIZE_FIELD_NUMBER;
        hash = (53 * hash) + getMultiHeadSize();
      }
      if (hasInteractingLayerNum()) {
        hash = (37 * hash) + INTERACTING_LAYER_NUM_FIELD_NUMBER;
        hash = (53 * hash) + getInteractingLayerNum();
      }
      if (hasL2Regularization()) {
        hash = (37 * hash) + L2_REGULARIZATION_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getL2Regularization());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.AutoInt}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.AutoInt)
        com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoIntOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.internal_static_protos_AutoInt_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.internal_static_protos_AutoInt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt.class, com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt.Builder.class);
      }

      // Construct using com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        multiHeadNum_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        multiHeadSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        interactingLayerNum_ = 1;
        bitField0_ = (bitField0_ & ~0x00000004);
        l2Regularization_ = 0.0001F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.internal_static_protos_AutoInt_descriptor;
      }

      @java.lang.Override
      public com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt getDefaultInstanceForType() {
        return com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt.getDefaultInstance();
      }

      @java.lang.Override
      public com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt build() {
        com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt buildPartial() {
        com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt result = new com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.multiHeadNum_ = multiHeadNum_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.multiHeadSize_ = multiHeadSize_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.interactingLayerNum_ = interactingLayerNum_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.l2Regularization_ = l2Regularization_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt) {
          return mergeFrom((com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt other) {
        if (other == com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt.getDefaultInstance()) return this;
        if (other.hasMultiHeadNum()) {
          setMultiHeadNum(other.getMultiHeadNum());
        }
        if (other.hasMultiHeadSize()) {
          setMultiHeadSize(other.getMultiHeadSize());
        }
        if (other.hasInteractingLayerNum()) {
          setInteractingLayerNum(other.getInteractingLayerNum());
        }
        if (other.hasL2Regularization()) {
          setL2Regularization(other.getL2Regularization());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasMultiHeadNum()) {
          return false;
        }
        if (!hasMultiHeadSize()) {
          return false;
        }
        if (!hasInteractingLayerNum()) {
          return false;
        }
        if (!hasL2Regularization()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int multiHeadNum_ = 1;
      /**
       * <pre>
       * The number of heads
       * </pre>
       *
       * <code>required uint32 multi_head_num = 1 [default = 1];</code>
       */
      public boolean hasMultiHeadNum() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * The number of heads
       * </pre>
       *
       * <code>required uint32 multi_head_num = 1 [default = 1];</code>
       */
      public int getMultiHeadNum() {
        return multiHeadNum_;
      }
      /**
       * <pre>
       * The number of heads
       * </pre>
       *
       * <code>required uint32 multi_head_num = 1 [default = 1];</code>
       */
      public Builder setMultiHeadNum(int value) {
        bitField0_ |= 0x00000001;
        multiHeadNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The number of heads
       * </pre>
       *
       * <code>required uint32 multi_head_num = 1 [default = 1];</code>
       */
      public Builder clearMultiHeadNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        multiHeadNum_ = 1;
        onChanged();
        return this;
      }

      private int multiHeadSize_ ;
      /**
       * <pre>
       * The dimension of heads
       * </pre>
       *
       * <code>required uint32 multi_head_size = 2;</code>
       */
      public boolean hasMultiHeadSize() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * The dimension of heads
       * </pre>
       *
       * <code>required uint32 multi_head_size = 2;</code>
       */
      public int getMultiHeadSize() {
        return multiHeadSize_;
      }
      /**
       * <pre>
       * The dimension of heads
       * </pre>
       *
       * <code>required uint32 multi_head_size = 2;</code>
       */
      public Builder setMultiHeadSize(int value) {
        bitField0_ |= 0x00000002;
        multiHeadSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The dimension of heads
       * </pre>
       *
       * <code>required uint32 multi_head_size = 2;</code>
       */
      public Builder clearMultiHeadSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        multiHeadSize_ = 0;
        onChanged();
        return this;
      }

      private int interactingLayerNum_ = 1;
      /**
       * <pre>
       * The number of interacting layers
       * </pre>
       *
       * <code>required uint32 interacting_layer_num = 3 [default = 1];</code>
       */
      public boolean hasInteractingLayerNum() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * The number of interacting layers
       * </pre>
       *
       * <code>required uint32 interacting_layer_num = 3 [default = 1];</code>
       */
      public int getInteractingLayerNum() {
        return interactingLayerNum_;
      }
      /**
       * <pre>
       * The number of interacting layers
       * </pre>
       *
       * <code>required uint32 interacting_layer_num = 3 [default = 1];</code>
       */
      public Builder setInteractingLayerNum(int value) {
        bitField0_ |= 0x00000004;
        interactingLayerNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The number of interacting layers
       * </pre>
       *
       * <code>required uint32 interacting_layer_num = 3 [default = 1];</code>
       */
      public Builder clearInteractingLayerNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        interactingLayerNum_ = 1;
        onChanged();
        return this;
      }

      private float l2Regularization_ = 0.0001F;
      /**
       * <code>required float l2_regularization = 4 [default = 0.0001];</code>
       */
      public boolean hasL2Regularization() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required float l2_regularization = 4 [default = 0.0001];</code>
       */
      public float getL2Regularization() {
        return l2Regularization_;
      }
      /**
       * <code>required float l2_regularization = 4 [default = 0.0001];</code>
       */
      public Builder setL2Regularization(float value) {
        bitField0_ |= 0x00000008;
        l2Regularization_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float l2_regularization = 4 [default = 0.0001];</code>
       */
      public Builder clearL2Regularization() {
        bitField0_ = (bitField0_ & ~0x00000008);
        l2Regularization_ = 0.0001F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protos.AutoInt)
    }

    // @@protoc_insertion_point(class_scope:protos.AutoInt)
    private static final com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt();
    }

    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AutoInt>
        PARSER = new com.google.protobuf.AbstractParser<AutoInt>() {
      @java.lang.Override
      public AutoInt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AutoInt(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AutoInt> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AutoInt> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.alibaba.alink.operator.batch.dl.ctr.protos.Autoint.AutoInt getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_AutoInt_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_AutoInt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$easy_rec/python/protos/autoint.proto\022\006" +
      "protos\"\202\001\n\007AutoInt\022\031\n\016multi_head_num\030\001 \002" +
      "(\r:\0011\022\027\n\017multi_head_size\030\002 \002(\r\022 \n\025intera" +
      "cting_layer_num\030\003 \002(\r:\0011\022!\n\021l2_regulariz" +
      "ation\030\004 \002(\002:\0060.0001B0\n.com.alibaba.alink" +
      ".operator.batch.dl.ctr.protos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protos_AutoInt_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_AutoInt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_AutoInt_descriptor,
        new java.lang.String[] { "MultiHeadNum", "MultiHeadSize", "InteractingLayerNum", "L2Regularization", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
