// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: easy_rec/python/protos/dnn.proto

package com.alibaba.alink.operator.batch.dl.ctr.protos;

public final class Dnn {
  private Dnn() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DNNOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.DNN)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * hidden units for each layer
     * </pre>
     *
     * <code>repeated uint32 hidden_units = 1;</code>
     */
    java.util.List<java.lang.Integer> getHiddenUnitsList();
    /**
     * <pre>
     * hidden units for each layer
     * </pre>
     *
     * <code>repeated uint32 hidden_units = 1;</code>
     */
    int getHiddenUnitsCount();
    /**
     * <pre>
     * hidden units for each layer
     * </pre>
     *
     * <code>repeated uint32 hidden_units = 1;</code>
     */
    int getHiddenUnits(int index);

    /**
     * <pre>
     * ratio of dropout
     * </pre>
     *
     * <code>repeated float dropout_ratio = 2;</code>
     */
    java.util.List<java.lang.Float> getDropoutRatioList();
    /**
     * <pre>
     * ratio of dropout
     * </pre>
     *
     * <code>repeated float dropout_ratio = 2;</code>
     */
    int getDropoutRatioCount();
    /**
     * <pre>
     * ratio of dropout
     * </pre>
     *
     * <code>repeated float dropout_ratio = 2;</code>
     */
    float getDropoutRatio(int index);

    /**
     * <pre>
     * activation function
     * </pre>
     *
     * <code>optional string activation = 3 [default = "tf.nn.relu"];</code>
     */
    boolean hasActivation();
    /**
     * <pre>
     * activation function
     * </pre>
     *
     * <code>optional string activation = 3 [default = "tf.nn.relu"];</code>
     */
    java.lang.String getActivation();
    /**
     * <pre>
     * activation function
     * </pre>
     *
     * <code>optional string activation = 3 [default = "tf.nn.relu"];</code>
     */
    com.google.protobuf.ByteString
        getActivationBytes();

    /**
     * <pre>
     * use batch normalization
     * </pre>
     *
     * <code>optional bool use_bn = 4 [default = true];</code>
     */
    boolean hasUseBn();
    /**
     * <pre>
     * use batch normalization
     * </pre>
     *
     * <code>optional bool use_bn = 4 [default = true];</code>
     */
    boolean getUseBn();
  }
  /**
   * Protobuf type {@code protos.DNN}
   */
  public  static final class DNN extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.DNN)
      DNNOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DNN.newBuilder() to construct.
    private DNN(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DNN() {
      hiddenUnits_ = emptyIntList();
      dropoutRatio_ = emptyFloatList();
      activation_ = "tf.nn.relu";
      useBn_ = true;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DNN();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DNN(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                hiddenUnits_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              hiddenUnits_.addInt(input.readUInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                hiddenUnits_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                hiddenUnits_.addInt(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 21: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                dropoutRatio_ = newFloatList();
                mutable_bitField0_ |= 0x00000002;
              }
              dropoutRatio_.addFloat(input.readFloat());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                dropoutRatio_ = newFloatList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                dropoutRatio_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              activation_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000002;
              useBn_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          hiddenUnits_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          dropoutRatio_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.internal_static_protos_DNN_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.internal_static_protos_DNN_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN.class, com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN.Builder.class);
    }

    private int bitField0_;
    public static final int HIDDEN_UNITS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.IntList hiddenUnits_;
    /**
     * <pre>
     * hidden units for each layer
     * </pre>
     *
     * <code>repeated uint32 hidden_units = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getHiddenUnitsList() {
      return hiddenUnits_;
    }
    /**
     * <pre>
     * hidden units for each layer
     * </pre>
     *
     * <code>repeated uint32 hidden_units = 1;</code>
     */
    public int getHiddenUnitsCount() {
      return hiddenUnits_.size();
    }
    /**
     * <pre>
     * hidden units for each layer
     * </pre>
     *
     * <code>repeated uint32 hidden_units = 1;</code>
     */
    public int getHiddenUnits(int index) {
      return hiddenUnits_.getInt(index);
    }

    public static final int DROPOUT_RATIO_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.FloatList dropoutRatio_;
    /**
     * <pre>
     * ratio of dropout
     * </pre>
     *
     * <code>repeated float dropout_ratio = 2;</code>
     */
    public java.util.List<java.lang.Float>
        getDropoutRatioList() {
      return dropoutRatio_;
    }
    /**
     * <pre>
     * ratio of dropout
     * </pre>
     *
     * <code>repeated float dropout_ratio = 2;</code>
     */
    public int getDropoutRatioCount() {
      return dropoutRatio_.size();
    }
    /**
     * <pre>
     * ratio of dropout
     * </pre>
     *
     * <code>repeated float dropout_ratio = 2;</code>
     */
    public float getDropoutRatio(int index) {
      return dropoutRatio_.getFloat(index);
    }

    public static final int ACTIVATION_FIELD_NUMBER = 3;
    private volatile java.lang.Object activation_;
    /**
     * <pre>
     * activation function
     * </pre>
     *
     * <code>optional string activation = 3 [default = "tf.nn.relu"];</code>
     */
    public boolean hasActivation() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * activation function
     * </pre>
     *
     * <code>optional string activation = 3 [default = "tf.nn.relu"];</code>
     */
    public java.lang.String getActivation() {
      java.lang.Object ref = activation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          activation_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * activation function
     * </pre>
     *
     * <code>optional string activation = 3 [default = "tf.nn.relu"];</code>
     */
    public com.google.protobuf.ByteString
        getActivationBytes() {
      java.lang.Object ref = activation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        activation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USE_BN_FIELD_NUMBER = 4;
    private boolean useBn_;
    /**
     * <pre>
     * use batch normalization
     * </pre>
     *
     * <code>optional bool use_bn = 4 [default = true];</code>
     */
    public boolean hasUseBn() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * use batch normalization
     * </pre>
     *
     * <code>optional bool use_bn = 4 [default = true];</code>
     */
    public boolean getUseBn() {
      return useBn_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < hiddenUnits_.size(); i++) {
        output.writeUInt32(1, hiddenUnits_.getInt(i));
      }
      for (int i = 0; i < dropoutRatio_.size(); i++) {
        output.writeFloat(2, dropoutRatio_.getFloat(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, activation_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBool(4, useBn_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < hiddenUnits_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(hiddenUnits_.getInt(i));
        }
        size += dataSize;
        size += 1 * getHiddenUnitsList().size();
      }
      {
        int dataSize = 0;
        dataSize = 4 * getDropoutRatioList().size();
        size += dataSize;
        size += 1 * getDropoutRatioList().size();
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, activation_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, useBn_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN)) {
        return super.equals(obj);
      }
      com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN other = (com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN) obj;

      if (!getHiddenUnitsList()
          .equals(other.getHiddenUnitsList())) return false;
      if (!getDropoutRatioList()
          .equals(other.getDropoutRatioList())) return false;
      if (hasActivation() != other.hasActivation()) return false;
      if (hasActivation()) {
        if (!getActivation()
            .equals(other.getActivation())) return false;
      }
      if (hasUseBn() != other.hasUseBn()) return false;
      if (hasUseBn()) {
        if (getUseBn()
            != other.getUseBn()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getHiddenUnitsCount() > 0) {
        hash = (37 * hash) + HIDDEN_UNITS_FIELD_NUMBER;
        hash = (53 * hash) + getHiddenUnitsList().hashCode();
      }
      if (getDropoutRatioCount() > 0) {
        hash = (37 * hash) + DROPOUT_RATIO_FIELD_NUMBER;
        hash = (53 * hash) + getDropoutRatioList().hashCode();
      }
      if (hasActivation()) {
        hash = (37 * hash) + ACTIVATION_FIELD_NUMBER;
        hash = (53 * hash) + getActivation().hashCode();
      }
      if (hasUseBn()) {
        hash = (37 * hash) + USE_BN_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getUseBn());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.DNN}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.DNN)
        com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNNOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.internal_static_protos_DNN_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.internal_static_protos_DNN_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN.class, com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN.Builder.class);
      }

      // Construct using com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        hiddenUnits_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        dropoutRatio_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000002);
        activation_ = "tf.nn.relu";
        bitField0_ = (bitField0_ & ~0x00000004);
        useBn_ = true;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.internal_static_protos_DNN_descriptor;
      }

      @java.lang.Override
      public com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN getDefaultInstanceForType() {
        return com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN.getDefaultInstance();
      }

      @java.lang.Override
      public com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN build() {
        com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN buildPartial() {
        com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN result = new com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          hiddenUnits_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.hiddenUnits_ = hiddenUnits_;
        if (((bitField0_ & 0x00000002) != 0)) {
          dropoutRatio_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.dropoutRatio_ = dropoutRatio_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.activation_ = activation_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.useBn_ = useBn_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN) {
          return mergeFrom((com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN other) {
        if (other == com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN.getDefaultInstance()) return this;
        if (!other.hiddenUnits_.isEmpty()) {
          if (hiddenUnits_.isEmpty()) {
            hiddenUnits_ = other.hiddenUnits_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureHiddenUnitsIsMutable();
            hiddenUnits_.addAll(other.hiddenUnits_);
          }
          onChanged();
        }
        if (!other.dropoutRatio_.isEmpty()) {
          if (dropoutRatio_.isEmpty()) {
            dropoutRatio_ = other.dropoutRatio_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDropoutRatioIsMutable();
            dropoutRatio_.addAll(other.dropoutRatio_);
          }
          onChanged();
        }
        if (other.hasActivation()) {
          bitField0_ |= 0x00000004;
          activation_ = other.activation_;
          onChanged();
        }
        if (other.hasUseBn()) {
          setUseBn(other.getUseBn());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList hiddenUnits_ = emptyIntList();
      private void ensureHiddenUnitsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          hiddenUnits_ = mutableCopy(hiddenUnits_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * hidden units for each layer
       * </pre>
       *
       * <code>repeated uint32 hidden_units = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getHiddenUnitsList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(hiddenUnits_) : hiddenUnits_;
      }
      /**
       * <pre>
       * hidden units for each layer
       * </pre>
       *
       * <code>repeated uint32 hidden_units = 1;</code>
       */
      public int getHiddenUnitsCount() {
        return hiddenUnits_.size();
      }
      /**
       * <pre>
       * hidden units for each layer
       * </pre>
       *
       * <code>repeated uint32 hidden_units = 1;</code>
       */
      public int getHiddenUnits(int index) {
        return hiddenUnits_.getInt(index);
      }
      /**
       * <pre>
       * hidden units for each layer
       * </pre>
       *
       * <code>repeated uint32 hidden_units = 1;</code>
       */
      public Builder setHiddenUnits(
          int index, int value) {
        ensureHiddenUnitsIsMutable();
        hiddenUnits_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * hidden units for each layer
       * </pre>
       *
       * <code>repeated uint32 hidden_units = 1;</code>
       */
      public Builder addHiddenUnits(int value) {
        ensureHiddenUnitsIsMutable();
        hiddenUnits_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * hidden units for each layer
       * </pre>
       *
       * <code>repeated uint32 hidden_units = 1;</code>
       */
      public Builder addAllHiddenUnits(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureHiddenUnitsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, hiddenUnits_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * hidden units for each layer
       * </pre>
       *
       * <code>repeated uint32 hidden_units = 1;</code>
       */
      public Builder clearHiddenUnits() {
        hiddenUnits_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.FloatList dropoutRatio_ = emptyFloatList();
      private void ensureDropoutRatioIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          dropoutRatio_ = mutableCopy(dropoutRatio_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       * ratio of dropout
       * </pre>
       *
       * <code>repeated float dropout_ratio = 2;</code>
       */
      public java.util.List<java.lang.Float>
          getDropoutRatioList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(dropoutRatio_) : dropoutRatio_;
      }
      /**
       * <pre>
       * ratio of dropout
       * </pre>
       *
       * <code>repeated float dropout_ratio = 2;</code>
       */
      public int getDropoutRatioCount() {
        return dropoutRatio_.size();
      }
      /**
       * <pre>
       * ratio of dropout
       * </pre>
       *
       * <code>repeated float dropout_ratio = 2;</code>
       */
      public float getDropoutRatio(int index) {
        return dropoutRatio_.getFloat(index);
      }
      /**
       * <pre>
       * ratio of dropout
       * </pre>
       *
       * <code>repeated float dropout_ratio = 2;</code>
       */
      public Builder setDropoutRatio(
          int index, float value) {
        ensureDropoutRatioIsMutable();
        dropoutRatio_.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ratio of dropout
       * </pre>
       *
       * <code>repeated float dropout_ratio = 2;</code>
       */
      public Builder addDropoutRatio(float value) {
        ensureDropoutRatioIsMutable();
        dropoutRatio_.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ratio of dropout
       * </pre>
       *
       * <code>repeated float dropout_ratio = 2;</code>
       */
      public Builder addAllDropoutRatio(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureDropoutRatioIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dropoutRatio_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ratio of dropout
       * </pre>
       *
       * <code>repeated float dropout_ratio = 2;</code>
       */
      public Builder clearDropoutRatio() {
        dropoutRatio_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private java.lang.Object activation_ = "tf.nn.relu";
      /**
       * <pre>
       * activation function
       * </pre>
       *
       * <code>optional string activation = 3 [default = "tf.nn.relu"];</code>
       */
      public boolean hasActivation() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * activation function
       * </pre>
       *
       * <code>optional string activation = 3 [default = "tf.nn.relu"];</code>
       */
      public java.lang.String getActivation() {
        java.lang.Object ref = activation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            activation_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * activation function
       * </pre>
       *
       * <code>optional string activation = 3 [default = "tf.nn.relu"];</code>
       */
      public com.google.protobuf.ByteString
          getActivationBytes() {
        java.lang.Object ref = activation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          activation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * activation function
       * </pre>
       *
       * <code>optional string activation = 3 [default = "tf.nn.relu"];</code>
       */
      public Builder setActivation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        activation_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * activation function
       * </pre>
       *
       * <code>optional string activation = 3 [default = "tf.nn.relu"];</code>
       */
      public Builder clearActivation() {
        bitField0_ = (bitField0_ & ~0x00000004);
        activation_ = getDefaultInstance().getActivation();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * activation function
       * </pre>
       *
       * <code>optional string activation = 3 [default = "tf.nn.relu"];</code>
       */
      public Builder setActivationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        activation_ = value;
        onChanged();
        return this;
      }

      private boolean useBn_ = true;
      /**
       * <pre>
       * use batch normalization
       * </pre>
       *
       * <code>optional bool use_bn = 4 [default = true];</code>
       */
      public boolean hasUseBn() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * use batch normalization
       * </pre>
       *
       * <code>optional bool use_bn = 4 [default = true];</code>
       */
      public boolean getUseBn() {
        return useBn_;
      }
      /**
       * <pre>
       * use batch normalization
       * </pre>
       *
       * <code>optional bool use_bn = 4 [default = true];</code>
       */
      public Builder setUseBn(boolean value) {
        bitField0_ |= 0x00000008;
        useBn_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * use batch normalization
       * </pre>
       *
       * <code>optional bool use_bn = 4 [default = true];</code>
       */
      public Builder clearUseBn() {
        bitField0_ = (bitField0_ & ~0x00000008);
        useBn_ = true;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protos.DNN)
    }

    // @@protoc_insertion_point(class_scope:protos.DNN)
    private static final com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN();
    }

    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DNN>
        PARSER = new com.google.protobuf.AbstractParser<DNN>() {
      @java.lang.Override
      public DNN parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DNN(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DNN> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DNN> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.alibaba.alink.operator.batch.dl.ctr.protos.Dnn.DNN getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_DNN_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_DNN_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n easy_rec/python/protos/dnn.proto\022\006prot" +
      "os\"h\n\003DNN\022\024\n\014hidden_units\030\001 \003(\r\022\025\n\rdropo" +
      "ut_ratio\030\002 \003(\002\022\036\n\nactivation\030\003 \001(\t:\ntf.n" +
      "n.relu\022\024\n\006use_bn\030\004 \001(\010:\004trueB0\n.com.alib" +
      "aba.alink.operator.batch.dl.ctr.protos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protos_DNN_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_DNN_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_DNN_descriptor,
        new java.lang.String[] { "HiddenUnits", "DropoutRatio", "Activation", "UseBn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
