// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: easy_rec/python/protos/esmm.proto

package com.alibaba.alink.operator.batch.dl.ctr.protos;

public final class Esmm {
  private Esmm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ESMMOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.ESMM)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protos.Tower groups = 1;</code>
     */
    java.util.List<com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower> 
        getGroupsList();
    /**
     * <code>repeated .protos.Tower groups = 1;</code>
     */
    com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower getGroups(int index);
    /**
     * <code>repeated .protos.Tower groups = 1;</code>
     */
    int getGroupsCount();
    /**
     * <code>repeated .protos.Tower groups = 1;</code>
     */
    java.util.List<? extends com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TowerOrBuilder> 
        getGroupsOrBuilderList();
    /**
     * <code>repeated .protos.Tower groups = 1;</code>
     */
    com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TowerOrBuilder getGroupsOrBuilder(
        int index);

    /**
     * <code>required .protos.TaskTower ctr_tower = 2;</code>
     */
    boolean hasCtrTower();
    /**
     * <code>required .protos.TaskTower ctr_tower = 2;</code>
     */
    com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower getCtrTower();
    /**
     * <code>required .protos.TaskTower ctr_tower = 2;</code>
     */
    com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTowerOrBuilder getCtrTowerOrBuilder();

    /**
     * <code>required .protos.TaskTower cvr_tower = 3;</code>
     */
    boolean hasCvrTower();
    /**
     * <code>required .protos.TaskTower cvr_tower = 3;</code>
     */
    com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower getCvrTower();
    /**
     * <code>required .protos.TaskTower cvr_tower = 3;</code>
     */
    com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTowerOrBuilder getCvrTowerOrBuilder();

    /**
     * <code>required float l2_regularization = 4 [default = 0.0001];</code>
     */
    boolean hasL2Regularization();
    /**
     * <code>required float l2_regularization = 4 [default = 0.0001];</code>
     */
    float getL2Regularization();
  }
  /**
   * Protobuf type {@code protos.ESMM}
   */
  public  static final class ESMM extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.ESMM)
      ESMMOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ESMM.newBuilder() to construct.
    private ESMM(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ESMM() {
      groups_ = java.util.Collections.emptyList();
      l2Regularization_ = 0.0001F;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ESMM();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ESMM(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                groups_ = new java.util.ArrayList<com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower>();
                mutable_bitField0_ |= 0x00000001;
              }
              groups_.add(
                  input.readMessage(com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = ctrTower_.toBuilder();
              }
              ctrTower_ = input.readMessage(com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ctrTower_);
                ctrTower_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 26: {
              com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = cvrTower_.toBuilder();
              }
              cvrTower_ = input.readMessage(com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cvrTower_);
                cvrTower_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 37: {
              bitField0_ |= 0x00000004;
              l2Regularization_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          groups_ = java.util.Collections.unmodifiableList(groups_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.internal_static_protos_ESMM_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.internal_static_protos_ESMM_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM.class, com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM.Builder.class);
    }

    private int bitField0_;
    public static final int GROUPS_FIELD_NUMBER = 1;
    private java.util.List<com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower> groups_;
    /**
     * <code>repeated .protos.Tower groups = 1;</code>
     */
    public java.util.List<com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower> getGroupsList() {
      return groups_;
    }
    /**
     * <code>repeated .protos.Tower groups = 1;</code>
     */
    public java.util.List<? extends com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TowerOrBuilder> 
        getGroupsOrBuilderList() {
      return groups_;
    }
    /**
     * <code>repeated .protos.Tower groups = 1;</code>
     */
    public int getGroupsCount() {
      return groups_.size();
    }
    /**
     * <code>repeated .protos.Tower groups = 1;</code>
     */
    public com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower getGroups(int index) {
      return groups_.get(index);
    }
    /**
     * <code>repeated .protos.Tower groups = 1;</code>
     */
    public com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TowerOrBuilder getGroupsOrBuilder(
        int index) {
      return groups_.get(index);
    }

    public static final int CTR_TOWER_FIELD_NUMBER = 2;
    private com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower ctrTower_;
    /**
     * <code>required .protos.TaskTower ctr_tower = 2;</code>
     */
    public boolean hasCtrTower() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .protos.TaskTower ctr_tower = 2;</code>
     */
    public com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower getCtrTower() {
      return ctrTower_ == null ? com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.getDefaultInstance() : ctrTower_;
    }
    /**
     * <code>required .protos.TaskTower ctr_tower = 2;</code>
     */
    public com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTowerOrBuilder getCtrTowerOrBuilder() {
      return ctrTower_ == null ? com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.getDefaultInstance() : ctrTower_;
    }

    public static final int CVR_TOWER_FIELD_NUMBER = 3;
    private com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower cvrTower_;
    /**
     * <code>required .protos.TaskTower cvr_tower = 3;</code>
     */
    public boolean hasCvrTower() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required .protos.TaskTower cvr_tower = 3;</code>
     */
    public com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower getCvrTower() {
      return cvrTower_ == null ? com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.getDefaultInstance() : cvrTower_;
    }
    /**
     * <code>required .protos.TaskTower cvr_tower = 3;</code>
     */
    public com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTowerOrBuilder getCvrTowerOrBuilder() {
      return cvrTower_ == null ? com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.getDefaultInstance() : cvrTower_;
    }

    public static final int L2_REGULARIZATION_FIELD_NUMBER = 4;
    private float l2Regularization_;
    /**
     * <code>required float l2_regularization = 4 [default = 0.0001];</code>
     */
    public boolean hasL2Regularization() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required float l2_regularization = 4 [default = 0.0001];</code>
     */
    public float getL2Regularization() {
      return l2Regularization_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCtrTower()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCvrTower()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasL2Regularization()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getGroupsCount(); i++) {
        if (!getGroups(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (!getCtrTower().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getCvrTower().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < groups_.size(); i++) {
        output.writeMessage(1, groups_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getCtrTower());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(3, getCvrTower());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeFloat(4, l2Regularization_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < groups_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, groups_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCtrTower());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getCvrTower());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, l2Regularization_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM)) {
        return super.equals(obj);
      }
      com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM other = (com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM) obj;

      if (!getGroupsList()
          .equals(other.getGroupsList())) return false;
      if (hasCtrTower() != other.hasCtrTower()) return false;
      if (hasCtrTower()) {
        if (!getCtrTower()
            .equals(other.getCtrTower())) return false;
      }
      if (hasCvrTower() != other.hasCvrTower()) return false;
      if (hasCvrTower()) {
        if (!getCvrTower()
            .equals(other.getCvrTower())) return false;
      }
      if (hasL2Regularization() != other.hasL2Regularization()) return false;
      if (hasL2Regularization()) {
        if (java.lang.Float.floatToIntBits(getL2Regularization())
            != java.lang.Float.floatToIntBits(
                other.getL2Regularization())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getGroupsCount() > 0) {
        hash = (37 * hash) + GROUPS_FIELD_NUMBER;
        hash = (53 * hash) + getGroupsList().hashCode();
      }
      if (hasCtrTower()) {
        hash = (37 * hash) + CTR_TOWER_FIELD_NUMBER;
        hash = (53 * hash) + getCtrTower().hashCode();
      }
      if (hasCvrTower()) {
        hash = (37 * hash) + CVR_TOWER_FIELD_NUMBER;
        hash = (53 * hash) + getCvrTower().hashCode();
      }
      if (hasL2Regularization()) {
        hash = (37 * hash) + L2_REGULARIZATION_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getL2Regularization());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.ESMM}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.ESMM)
        com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMMOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.internal_static_protos_ESMM_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.internal_static_protos_ESMM_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM.class, com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM.Builder.class);
      }

      // Construct using com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getGroupsFieldBuilder();
          getCtrTowerFieldBuilder();
          getCvrTowerFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (groupsBuilder_ == null) {
          groups_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          groupsBuilder_.clear();
        }
        if (ctrTowerBuilder_ == null) {
          ctrTower_ = null;
        } else {
          ctrTowerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (cvrTowerBuilder_ == null) {
          cvrTower_ = null;
        } else {
          cvrTowerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        l2Regularization_ = 0.0001F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.internal_static_protos_ESMM_descriptor;
      }

      @java.lang.Override
      public com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM getDefaultInstanceForType() {
        return com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM.getDefaultInstance();
      }

      @java.lang.Override
      public com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM build() {
        com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM buildPartial() {
        com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM result = new com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (groupsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            groups_ = java.util.Collections.unmodifiableList(groups_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.groups_ = groups_;
        } else {
          result.groups_ = groupsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (ctrTowerBuilder_ == null) {
            result.ctrTower_ = ctrTower_;
          } else {
            result.ctrTower_ = ctrTowerBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          if (cvrTowerBuilder_ == null) {
            result.cvrTower_ = cvrTower_;
          } else {
            result.cvrTower_ = cvrTowerBuilder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.l2Regularization_ = l2Regularization_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM) {
          return mergeFrom((com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM other) {
        if (other == com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM.getDefaultInstance()) return this;
        if (groupsBuilder_ == null) {
          if (!other.groups_.isEmpty()) {
            if (groups_.isEmpty()) {
              groups_ = other.groups_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGroupsIsMutable();
              groups_.addAll(other.groups_);
            }
            onChanged();
          }
        } else {
          if (!other.groups_.isEmpty()) {
            if (groupsBuilder_.isEmpty()) {
              groupsBuilder_.dispose();
              groupsBuilder_ = null;
              groups_ = other.groups_;
              bitField0_ = (bitField0_ & ~0x00000001);
              groupsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getGroupsFieldBuilder() : null;
            } else {
              groupsBuilder_.addAllMessages(other.groups_);
            }
          }
        }
        if (other.hasCtrTower()) {
          mergeCtrTower(other.getCtrTower());
        }
        if (other.hasCvrTower()) {
          mergeCvrTower(other.getCvrTower());
        }
        if (other.hasL2Regularization()) {
          setL2Regularization(other.getL2Regularization());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasCtrTower()) {
          return false;
        }
        if (!hasCvrTower()) {
          return false;
        }
        if (!hasL2Regularization()) {
          return false;
        }
        for (int i = 0; i < getGroupsCount(); i++) {
          if (!getGroups(i).isInitialized()) {
            return false;
          }
        }
        if (!getCtrTower().isInitialized()) {
          return false;
        }
        if (!getCvrTower().isInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower> groups_ =
        java.util.Collections.emptyList();
      private void ensureGroupsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          groups_ = new java.util.ArrayList<com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower>(groups_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower.Builder, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TowerOrBuilder> groupsBuilder_;

      /**
       * <code>repeated .protos.Tower groups = 1;</code>
       */
      public java.util.List<com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower> getGroupsList() {
        if (groupsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(groups_);
        } else {
          return groupsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protos.Tower groups = 1;</code>
       */
      public int getGroupsCount() {
        if (groupsBuilder_ == null) {
          return groups_.size();
        } else {
          return groupsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protos.Tower groups = 1;</code>
       */
      public com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower getGroups(int index) {
        if (groupsBuilder_ == null) {
          return groups_.get(index);
        } else {
          return groupsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protos.Tower groups = 1;</code>
       */
      public Builder setGroups(
          int index, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower value) {
        if (groupsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGroupsIsMutable();
          groups_.set(index, value);
          onChanged();
        } else {
          groupsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.Tower groups = 1;</code>
       */
      public Builder setGroups(
          int index, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower.Builder builderForValue) {
        if (groupsBuilder_ == null) {
          ensureGroupsIsMutable();
          groups_.set(index, builderForValue.build());
          onChanged();
        } else {
          groupsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.Tower groups = 1;</code>
       */
      public Builder addGroups(com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower value) {
        if (groupsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGroupsIsMutable();
          groups_.add(value);
          onChanged();
        } else {
          groupsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.Tower groups = 1;</code>
       */
      public Builder addGroups(
          int index, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower value) {
        if (groupsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGroupsIsMutable();
          groups_.add(index, value);
          onChanged();
        } else {
          groupsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.Tower groups = 1;</code>
       */
      public Builder addGroups(
          com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower.Builder builderForValue) {
        if (groupsBuilder_ == null) {
          ensureGroupsIsMutable();
          groups_.add(builderForValue.build());
          onChanged();
        } else {
          groupsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.Tower groups = 1;</code>
       */
      public Builder addGroups(
          int index, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower.Builder builderForValue) {
        if (groupsBuilder_ == null) {
          ensureGroupsIsMutable();
          groups_.add(index, builderForValue.build());
          onChanged();
        } else {
          groupsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.Tower groups = 1;</code>
       */
      public Builder addAllGroups(
          java.lang.Iterable<? extends com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower> values) {
        if (groupsBuilder_ == null) {
          ensureGroupsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, groups_);
          onChanged();
        } else {
          groupsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protos.Tower groups = 1;</code>
       */
      public Builder clearGroups() {
        if (groupsBuilder_ == null) {
          groups_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          groupsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protos.Tower groups = 1;</code>
       */
      public Builder removeGroups(int index) {
        if (groupsBuilder_ == null) {
          ensureGroupsIsMutable();
          groups_.remove(index);
          onChanged();
        } else {
          groupsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protos.Tower groups = 1;</code>
       */
      public com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower.Builder getGroupsBuilder(
          int index) {
        return getGroupsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protos.Tower groups = 1;</code>
       */
      public com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TowerOrBuilder getGroupsOrBuilder(
          int index) {
        if (groupsBuilder_ == null) {
          return groups_.get(index);  } else {
          return groupsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protos.Tower groups = 1;</code>
       */
      public java.util.List<? extends com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TowerOrBuilder> 
           getGroupsOrBuilderList() {
        if (groupsBuilder_ != null) {
          return groupsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(groups_);
        }
      }
      /**
       * <code>repeated .protos.Tower groups = 1;</code>
       */
      public com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower.Builder addGroupsBuilder() {
        return getGroupsFieldBuilder().addBuilder(
            com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.Tower groups = 1;</code>
       */
      public com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower.Builder addGroupsBuilder(
          int index) {
        return getGroupsFieldBuilder().addBuilder(
            index, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.Tower groups = 1;</code>
       */
      public java.util.List<com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower.Builder> 
           getGroupsBuilderList() {
        return getGroupsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower.Builder, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TowerOrBuilder> 
          getGroupsFieldBuilder() {
        if (groupsBuilder_ == null) {
          groupsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.Tower.Builder, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TowerOrBuilder>(
                  groups_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          groups_ = null;
        }
        return groupsBuilder_;
      }

      private com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower ctrTower_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.Builder, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTowerOrBuilder> ctrTowerBuilder_;
      /**
       * <code>required .protos.TaskTower ctr_tower = 2;</code>
       */
      public boolean hasCtrTower() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required .protos.TaskTower ctr_tower = 2;</code>
       */
      public com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower getCtrTower() {
        if (ctrTowerBuilder_ == null) {
          return ctrTower_ == null ? com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.getDefaultInstance() : ctrTower_;
        } else {
          return ctrTowerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protos.TaskTower ctr_tower = 2;</code>
       */
      public Builder setCtrTower(com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower value) {
        if (ctrTowerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ctrTower_ = value;
          onChanged();
        } else {
          ctrTowerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protos.TaskTower ctr_tower = 2;</code>
       */
      public Builder setCtrTower(
          com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.Builder builderForValue) {
        if (ctrTowerBuilder_ == null) {
          ctrTower_ = builderForValue.build();
          onChanged();
        } else {
          ctrTowerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protos.TaskTower ctr_tower = 2;</code>
       */
      public Builder mergeCtrTower(com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower value) {
        if (ctrTowerBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              ctrTower_ != null &&
              ctrTower_ != com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.getDefaultInstance()) {
            ctrTower_ =
              com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.newBuilder(ctrTower_).mergeFrom(value).buildPartial();
          } else {
            ctrTower_ = value;
          }
          onChanged();
        } else {
          ctrTowerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protos.TaskTower ctr_tower = 2;</code>
       */
      public Builder clearCtrTower() {
        if (ctrTowerBuilder_ == null) {
          ctrTower_ = null;
          onChanged();
        } else {
          ctrTowerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .protos.TaskTower ctr_tower = 2;</code>
       */
      public com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.Builder getCtrTowerBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCtrTowerFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protos.TaskTower ctr_tower = 2;</code>
       */
      public com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTowerOrBuilder getCtrTowerOrBuilder() {
        if (ctrTowerBuilder_ != null) {
          return ctrTowerBuilder_.getMessageOrBuilder();
        } else {
          return ctrTower_ == null ?
              com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.getDefaultInstance() : ctrTower_;
        }
      }
      /**
       * <code>required .protos.TaskTower ctr_tower = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.Builder, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTowerOrBuilder> 
          getCtrTowerFieldBuilder() {
        if (ctrTowerBuilder_ == null) {
          ctrTowerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.Builder, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTowerOrBuilder>(
                  getCtrTower(),
                  getParentForChildren(),
                  isClean());
          ctrTower_ = null;
        }
        return ctrTowerBuilder_;
      }

      private com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower cvrTower_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.Builder, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTowerOrBuilder> cvrTowerBuilder_;
      /**
       * <code>required .protos.TaskTower cvr_tower = 3;</code>
       */
      public boolean hasCvrTower() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required .protos.TaskTower cvr_tower = 3;</code>
       */
      public com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower getCvrTower() {
        if (cvrTowerBuilder_ == null) {
          return cvrTower_ == null ? com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.getDefaultInstance() : cvrTower_;
        } else {
          return cvrTowerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protos.TaskTower cvr_tower = 3;</code>
       */
      public Builder setCvrTower(com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower value) {
        if (cvrTowerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cvrTower_ = value;
          onChanged();
        } else {
          cvrTowerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .protos.TaskTower cvr_tower = 3;</code>
       */
      public Builder setCvrTower(
          com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.Builder builderForValue) {
        if (cvrTowerBuilder_ == null) {
          cvrTower_ = builderForValue.build();
          onChanged();
        } else {
          cvrTowerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .protos.TaskTower cvr_tower = 3;</code>
       */
      public Builder mergeCvrTower(com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower value) {
        if (cvrTowerBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
              cvrTower_ != null &&
              cvrTower_ != com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.getDefaultInstance()) {
            cvrTower_ =
              com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.newBuilder(cvrTower_).mergeFrom(value).buildPartial();
          } else {
            cvrTower_ = value;
          }
          onChanged();
        } else {
          cvrTowerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .protos.TaskTower cvr_tower = 3;</code>
       */
      public Builder clearCvrTower() {
        if (cvrTowerBuilder_ == null) {
          cvrTower_ = null;
          onChanged();
        } else {
          cvrTowerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .protos.TaskTower cvr_tower = 3;</code>
       */
      public com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.Builder getCvrTowerBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getCvrTowerFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protos.TaskTower cvr_tower = 3;</code>
       */
      public com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTowerOrBuilder getCvrTowerOrBuilder() {
        if (cvrTowerBuilder_ != null) {
          return cvrTowerBuilder_.getMessageOrBuilder();
        } else {
          return cvrTower_ == null ?
              com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.getDefaultInstance() : cvrTower_;
        }
      }
      /**
       * <code>required .protos.TaskTower cvr_tower = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.Builder, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTowerOrBuilder> 
          getCvrTowerFieldBuilder() {
        if (cvrTowerBuilder_ == null) {
          cvrTowerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTower.Builder, com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.TaskTowerOrBuilder>(
                  getCvrTower(),
                  getParentForChildren(),
                  isClean());
          cvrTower_ = null;
        }
        return cvrTowerBuilder_;
      }

      private float l2Regularization_ = 0.0001F;
      /**
       * <code>required float l2_regularization = 4 [default = 0.0001];</code>
       */
      public boolean hasL2Regularization() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required float l2_regularization = 4 [default = 0.0001];</code>
       */
      public float getL2Regularization() {
        return l2Regularization_;
      }
      /**
       * <code>required float l2_regularization = 4 [default = 0.0001];</code>
       */
      public Builder setL2Regularization(float value) {
        bitField0_ |= 0x00000008;
        l2Regularization_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float l2_regularization = 4 [default = 0.0001];</code>
       */
      public Builder clearL2Regularization() {
        bitField0_ = (bitField0_ & ~0x00000008);
        l2Regularization_ = 0.0001F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protos.ESMM)
    }

    // @@protoc_insertion_point(class_scope:protos.ESMM)
    private static final com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM();
    }

    public static com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ESMM>
        PARSER = new com.google.protobuf.AbstractParser<ESMM>() {
      @java.lang.Override
      public ESMM parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ESMM(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ESMM> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ESMM> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.alibaba.alink.operator.batch.dl.ctr.protos.Esmm.ESMM getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_ESMM_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_ESMM_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!easy_rec/python/protos/esmm.proto\022\006pro" +
      "tos\032\"easy_rec/python/protos/tower.proto\"" +
      "\224\001\n\004ESMM\022\035\n\006groups\030\001 \003(\0132\r.protos.Tower\022" +
      "$\n\tctr_tower\030\002 \002(\0132\021.protos.TaskTower\022$\n" +
      "\tcvr_tower\030\003 \002(\0132\021.protos.TaskTower\022!\n\021l" +
      "2_regularization\030\004 \002(\002:\0060.0001B0\n.com.al" +
      "ibaba.alink.operator.batch.dl.ctr.protos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.getDescriptor(),
        });
    internal_static_protos_ESMM_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_ESMM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_ESMM_descriptor,
        new java.lang.String[] { "Groups", "CtrTower", "CvrTower", "L2Regularization", });
    com.alibaba.alink.operator.batch.dl.ctr.protos.TowerOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
